package model

type QuestionnaireBehavioralQuestion struct {
	Id      int64  `json:"id"`
	Title   string `json:"title"`
	AnswerA string `json:"answer_a"`
	AnswerB string `json:"answer_b"`
}

var QuestionnaireBehavioral = []QuestionnaireBehavioralQuestion{
	{Id: 1, Title: "Suas melhores idéias no trabalho vêm de", AnswerA: "uma troca de idéias e compartilhamento com outras pessoas, ou", AnswerB: "seus pensamentos individuais?"},
	{Id: 2, Title: "Você prefere reuniões nas quais a maior parte do tempo é usada", AnswerA: "com aplicação das idéias, ou", AnswerB: "com discussão das idéias em si?"},
	{Id: 3, Title: "Você prefere um ambiente de trabalho em que", AnswerA: "conflitos freqüentes geram discussões e idéias interessantes, ou", AnswerB: "a harmonia é valorizada e o conflito é evitado?"},
	{Id: 4, Title: "Você prefere que o local onde você trabalha seja", AnswerA: "estruturado com regras e regulamentos claros, ou", AnswerB: "mais aberto, sem interferências?"},
	{Id: 5, Title: "Você prefere ter um supervisor com quem você tem", AnswerA: "muita interação no dia-a-dia ou", AnswerB: "somente interação esporádica?"},
	//{Id: 6, Title: "Se seu chefe te dá uma tarefa difícil, você costuma", AnswerA: "coletar o máximo de informações possível antes de iniciar, ou", AnswerB: "já seguir em frente para resolver as coisas?"},
	//{Id: 7, Title: "Em uma avaliação de desempenho, você prefere que seu chefe escreva", AnswerA: "que você é inteligente e razoável, ou", AnswerB: "que você é caloroso e gentil?"},
	//{Id: 8, Title: "Você prefere projetos no trabalho", AnswerA: "bem definidos e planejados, ou", AnswerB: "que permitam uma interpretação flexível?"},
	//{Id: 9, Title: "Você prefere passar a hora do almoço", AnswerA: "comendo com um grupo, ou", AnswerB: "comendo sozinho ou com um colega próximo?"},
	//{Id: 10, Title: "Quando uma nova idéia surge em sua mente, você costuma", AnswerA: "querer testá-la cuidadosamente antes de se entusiasmar, ou", AnswerB: "ficar entusiasmado e querer implementá-la rapidamente?"},
	//{Id: 11, Title: "Se você tiver que confrontar colegas ou subordinados, você geralmente", AnswerA: "quer garantir que apresentou todo os fatos com precisão, ou", AnswerB: "se interessa mais em garantir que não vai machucar os sentimentos deles?"},
	//{Id: 12, Title: "Você prefere", AnswerA: "planejar seu dia de trabalho com antecedência ou", AnswerB: "deixar o dia progredir e ver como as coisas acabam?"},
	//{Id: 13, Title: "Se você tivesse um escritório, você preferiria trabalhar com a porta", AnswerA: "aberta, ou", AnswerB: "fechada?"},
	//{Id: 14, Title: "Quando você resolve problemas, é mais provável que você", AnswerA: "se concentre nos fatos observados, ou", AnswerB: "explore todas as possibilidades?"},
	//{Id: 15, Title: "Quando se depara com uma decisão no trabalho, você prefere", AnswerA: "ponderar sobre as coisas, ou", AnswerB: "confia em seus sentimentos?"},
	//{Id: 16, Title: "Você prefere um trabalho em que as recompensas", AnswerA: "são claramente definidas de tempos em tempos, ou", AnswerB: "são mantidas por longos períodos de tempo?"},
	//{Id: 17, Title: "Você prefere que a maioria dos seus trabalhos sejam", AnswerA: "uma série contínua de tarefas curtas, ou", AnswerB: "projetos longos nos quais você pode concentrar seus esforços?"},
	//{Id: 18, Title: "Você prefere que seu chefe peça para você resolver", AnswerA: "problemas práticos, ou", AnswerB: "problemas de políticas e procedimentos?"},
	//{Id: 19, Title: "Quando se depara com uma decisão no trabalho, você costuma", AnswerA: "concentre-se nos fatos e números, acima de tudo, ou", AnswerB: "dar atenção cuidadosa aos sentimentos das pessoas?"},
	//{Id: 20, Title: "Você prefere ter um chefe que", AnswerA: "te forneça muita estrutura e organização, ou", AnswerB: "deixa você fazer as coisas como funcionam melhor para você?"},
	//{Id: 21, Title: "Quando você almoça com seus colegas, você prefere", AnswerA: "falar sobre pessoas, ou", AnswerB: "falar sobre Ideias?"},
	//{Id: 22, Title: "Você acha que seus colegas veem você mais como", AnswerA: "uma pessoa aqui e agora, ou", AnswerB: "alguém focado no futuro?"},
	//{Id: 23, Title: "Se alguém argumenta uma política ou decisão que você toma, você costuma", AnswerA: "permanecer firme, ou", AnswerB: "procura evitar mal estar, raiva e desarmonia?"},
	//{Id: 24, Title: "Você prefere que o seu trabalho do dia a dia", AnswerA: "seja mais uma rotina contínua, ou", AnswerB: "tenha mudanças frequentes em atividades e horários?"},
	//{Id: 25, Title: "Você prefere ter", AnswerA: "um grande grupo de colegas de trabalho, ou", AnswerB: "alguns colegas que você conhece bem?"},
	//{Id: 26, Title: "Quando colegas ou subordinados apresentam idéias para você, você prefere", AnswerA: "idéias conhecidas e imediatamente úteis, ou", AnswerB: "idéias com abordagens inovadoras?"},
	//{Id: 27, Title: "Você prefere trabalhar com colegas que", AnswerA: "confiam fortemente na lógica, ou", AnswerB: "olham mais frequentemente para seus sentimentos?"},
	//{Id: 28, Title: "Quando seu chefe lhe oferece um novo projeto, você geralmente prefere", AnswerA: "uma explicação clara do que é esperado, ou", AnswerB: "ser deixado para trabalhar do jeito que você achar melhor?"},
	//{Id: 29, Title: "Se você vai a um passeio da empresa, você prefere", AnswerA: "encontrar pessoas que você pode conhecer melhor agora ou", AnswerB: "sair com os colegas que você conhece bem?"},
	//{Id: 30, Title: "Você prefere um emprego onde possa", AnswerA: "usar sua experiência para trabalhar em tarefas que lhe são familiares, ou", AnswerB: "lidar com idéias e problemas que são novos para você?"},
	//{Id: 31, Title: "Se você precisa lidar com os sentimentos de um colega, você prefere ser", AnswerA: "sincero, mesmo que você não possa ser diplomático, ou", AnswerB: "diplomático, mesmo que você não possa dizer a verdade?"},
	//{Id: 32, Title: "Você prefere que seu ambiente de trabalho seja", AnswerA: "confortável, previsível e estável, ou", AnswerB: "flexível e mutável?"},
	//{Id: 33, Title: "Seus colegas de trabalho provavelmente o descreveriam como", AnswerA: "um membro da equipe cheio de energia, ou", AnswerB: "um funcionário quieto e pensativo?"},
	//{Id: 34, Title: "Quando você participa de um treinamento, você geralmente prefere", AnswerA: "treinamento com experienciais, ou", AnswerB: "Treinamento com informações e ensinamentos teóricos?"},
	//{Id: 35, Title: "Quando você tem uma reunião com um colega, você costuma", AnswerA: "resolver rapidamente de maneira profissional, ou", AnswerB: "permanecer interagindo socialmente?"},
	//{Id: 36, Title: "Se alguém da sua equipe está atrasado com uma tarefa planejada, você normalmente", AnswerA: "fica impaciente e irritado, ou", AnswerB: "é aberto e flexível em rever os prazos?"},
	//{Id: 37, Title: "Quando você participa de um treinamento, é mais provável que você", AnswerA: "participe aberta e ativamente, ou", AnswerB: "deixe que outros assumam o papel ativo?"},
	//{Id: 38, Title: "Você tem mais probabilidade de", AnswerA: "lembrar dos fatos apresentados em uma reunião ou documento, ou", AnswerB: "lembrar principalmente dos conceitos apresentados?"},
	//{Id: 39, Title: "Quando os colegas pedem conselhos sobre um assunto de trabalho, você costuma", AnswerA: "ajudá-los a tomar uma decisão lógica, ou", AnswerB: "ajudá-los a explorar os valores e políticas da empresa naquela situação"},
	//{Id: 40, Title: "Se um subordinado (ou colega) vem até você para explicar uma dificuldade em fazer algo dentro do prazo, você geralmente", AnswerA: "fica contrariado, ou", AnswerB: "O ajuda a encontrar uma abordagem que estenda o prazo?"},
	//{Id: 41, Title: "Quando você tem uma decisão para tomar no trabalho, você com mais frequência", AnswerA: "conversa com várias pessoas antes de decidir, ou", AnswerB: "passa a maior parte do tempo trabalhando o assunto na cabeça?"},
	//{Id: 42, Title: "Quando você lê um relatório, costuma ir primeiro", AnswerA: "à parte de informações detalhadas, ou", AnswerB: "ao resumo, ou visão geral do relatório?"},
	//{Id: 43, Title: "Quando você está propondo uma nova idéia no trabalho, você costuma", AnswerA: "permanecer firme quanto a sua certeza de que a idéia é correta, ou", AnswerB: "tentar persuadir os outros apelando ao seu senso de valor?"},
	//{Id: 44, Title: "Você prefere estar em um trabalho com", AnswerA: "atividades que exigem que você chegue a uma conclusão ou", AnswerB: "atividades que te permitem obter experiências?"},
	//{Id: 45, Title: "Você está mais interessado em", AnswerA: "tarefas reais que você está realizando no dia-a-dia, ou", AnswerB: "seus pensamentos sobre o seu trabalho?"},
	//{Id: 46, Title: "Em uma avaliação de desempenho, seria mais preciso se seu chefe dissesse", AnswerA: "que você é prático, ou", AnswerB: "que você é criativo?"},
	//{Id: 47, Title: "Você geralmente está mais interessado em saber como seus colegas", AnswerA: "pensam sobre os problemas, ou", AnswerB: "sentem sobre os problemas?"},
	//{Id: 48, Title: "Se seu chefe insistir que você planeje seu dia de trabalho, você sente", AnswerA: "satisfeito em ficar organizado, ou", AnswerB: "desconfortável por se sentir constrangido?"},
	//{Id: 49, Title: "Quando você pede conselhos ou ajuda a um colega, geralmente você", AnswerA: "se sente confortável, ou", AnswerB: "se sente um pouco desconfortável?"},
	//{Id: 50, Title: "Quando você inicia um novo projeto, você costuma", AnswerA: "escrever um plano passo a passo no início do processo ou", AnswerB: "primeiro esperar e ver como as coisas se desenvolvem?"},
	//{Id: 51, Title: "Quando você tem uma decisão a tomar no trabalho, você geralmente", AnswerA: "raciocina, independentemente de seus sentimentos, ou", AnswerB: "considera a importância dos seus sentimentos?"},
	//{Id: 52, Title: "Quando o anúncio de uma política nova e incomum é feito no trabalho, você geralmente fica", AnswerA: "irritado ou chateado com as mudanças, ou", AnswerB: "interessado em ver como você irá lidar com o novo ambiente?"},
	//{Id: 53, Title: "Quando você é interrompido no meio de um trabalho difícil, você costuma", AnswerA: "gostar da oportunidade de conversar com alguém, ou", AnswerB: "preferir ficar sozinho com seus pensamentos?"},
	//{Id: 54, Title: "Você costuma trabalhar onde possa", AnswerA: "utilizar sua natureza e habilidades práticas, ou", AnswerB: "utilizar sua capacidade de criar novas idéias e coisas?"},
	//{Id: 55, Title: "Quando você precisa tomar uma decisão no trabalho, é mais provável que você", AnswerA: "analise a situação de forma lógica, ou", AnswerB: "coloque uma forte ênfase em aplicar seus valores à solução?"},
	//{Id: 56, Title: "Se eles não pudessem ser os dois, você prefere ter colegas que são", AnswerA: "bem organizados, ou", AnswerB: "espontâneos?"},
	//{Id: 57, Title: "Você prefere trabalhar em uma empresa onde", AnswerA: "todos trabalham juntos em um ambiente aberto e ativo, ou", AnswerB: "as pessoas trabalham independentes em seus próprios espaços?"},
	//{Id: 58, Title: "Se você é ou fosse um líder, seu estilo de liderança é mais", AnswerA: "prático ou", AnswerB: "visionário?"},
	//{Id: 59, Title: "Em uma reunião de avaliação de desempenho, é mais provável que você", AnswerA: "seja franco e honesto, independentemente de sentimentos, ou", AnswerB: "tente suavizar qualquer problema e evitar sentimentos feridos?"},
	//{Id: 60, Title: "Quando você está discutindo uma questão importante em uma reunião, geralmente você", AnswerA: "tenta chegar rapidamente a uma conclusão definitiva, ou", AnswerB: "mantém opções abertas?"},
	//{Id: 61, Title: "Quando você precisa transmitir uma idéia ou informação, você prefere", AnswerA: "falar diretamente com as pessoas, ou", AnswerB: "transmitir por escrito?"},
	//{Id: 62, Title: "Você prefere uma situação de trabalho que seja", AnswerA: "estável com poucas mudanças, ou", AnswerB: "cheia de mudanças?"},
	//{Id: 63, Title: "Seria mais provável que seus colegas descrevessem seu comportamento no trabalho como", AnswerA: "frio e objetivo, ou", AnswerB: "caloroso e sentimental?"},
	//{Id: 64, Title: "No trabalho, você tende a", AnswerA: "focar fortemente em concluir as coisas dentro do prazo, ou", AnswerB: "ser flexível sobre a mudança de prazos?"},
	//{Id: 65, Title: "Você gosta mais de", AnswerA: "um dia de trabalho cheio de variedade e interações com outras pessoas, ou", AnswerB: "trabalhar por periodos de tempo sem interagir com outras pessoas?"},
	//{Id: 66, Title: "Quando você pensa nas atividades mais importantes de trabalho, elas são", AnswerA: "mais inclinadas para a prática, ou", AnswerB: "mais inclinadas para as ideias?"},
	//{Id: 67, Title: "Em uma sessão ou curso de treinamento, você prefere um instrutor que seja", AnswerA: "conciso, lógico e direto ao ponto, ou", AnswerB: "genuíno e comovente?"},
	//{Id: 68, Title: "Quando necessaário, você costuma pressionar seus colegas ou subordinados para", AnswerA: "decisões rápidas ou", AnswerB: "revisão completa, mesmo correndo o risco de atrasar as decisões?"},
}
