package model

type QuestionnaireProfessionalQuestion struct {
	Id      int64  `json:"id"`
	AnswerA string `json:"answer_a"`
	AnswerB string `json:"answer_b"`
}

type Category struct {
	AnswerA int64 `json:"answer_a"`
	AnswerB int64 `json:"answer_b"`
}

var QuestionnaireProfessional = []QuestionnaireProfessionalQuestion{
	{Id: 1, AnswerA: "Gosto de fazer um trabalho bem feito", AnswerB: "Gosto de movimentar-me"},
	{Id: 2, AnswerA: "Dizem que sou inflexível", AnswerB: "Gosto de atuar em equipe"},
	{Id: 3, AnswerA: "As pessoas não me dão ouvidos", AnswerB: "Dizem que sou muito cordial"},
	{Id: 4, AnswerA: "Sempre admiro meus superiores", AnswerB: "Gosto de ser diferente das outras pessoas"},
	{Id: 5, AnswerA: "Sou atirado ( afoito)", AnswerB: "Não gosto de improvisação"},
	{Id: 6, AnswerA: "Quando me tratam com injustiça, discuto muito", AnswerB: "Agrada-me ter subordinados"},
	{Id: 7, AnswerA: "Executo meu trabalho com pressa em terminá-lo", AnswerB: "Gosto de lidar com minúcias"},
	{Id: 8, AnswerA: "Preocupo-me quando não gostam de mim", AnswerB: "Tenho necessidade de terminar o que iniciei"},
	{Id: 9, AnswerA: "Gosto de ser alvo de atenções no grupo", AnswerB: "Sinto-me bem executando um trabalho difícil"},
	{Id: 10, AnswerA: "Nas horas de folga eu faço ginástica", AnswerB: "Normalmente sou controlado"},
	{Id: 11, AnswerA: "Gosto de fazer amigos", AnswerB: "Não me aborreço com facilidade"},
	{Id: 12, AnswerA: "Gosto de fazer um trabalho o mais rápido possível", AnswerB: "Aborreço-me quando não deixam os objetos em seus lugares"},
	{Id: 13, AnswerA: "Gosto de inovações", AnswerB: "Procuro acabar o que começo"},
	{Id: 14, AnswerA: "Decido com rapidez", AnswerB: "Interesso-me por detalhes"},
	{Id: 15, AnswerA: "Sou muito franco", AnswerB: "Sempre tento ser o melhor"},
	{Id: 16, AnswerA: "Gosto de trabalhar em posição de comando", AnswerB: "Gosto de pensar e planejar"},
	{Id: 17, AnswerA: "Agrada-me se o meu superior gosta de mim", AnswerB: "Gosto de mandar"},
	{Id: 18, AnswerA: "Dedico-me ao trabalho em excesso", AnswerB: "Faço amizade com facilidade"},
	{Id: 19, AnswerA: "Gosto de instruções objetivas", AnswerB: "Aborreço-me se, em grupo, não me dão atenção"},
	{Id: 20, AnswerA: "Às vezes conto algumas vantagens sobre meu trabalho", AnswerB: "As pessoas me entendem"},
	{Id: 21, AnswerA: "Em qualquer atividade sou esforçado", AnswerB: "Prefiro prazos curtos para entregar os resultados"},
	{Id: 22, AnswerA: "Discuto pouco com o meu superior", AnswerB: "Faço concessões para participar da equipe"},
	{Id: 23, AnswerA: "Dizem que sou bom líder", AnswerB: "Tenho habilidade manual"},
	{Id: 24, AnswerA: "Sempre defendo meu ponto de vista", AnswerB: "Gosto de ser notado pelo grupo"},
	{Id: 25, AnswerA: "Tenho dificuldade em fazer amigos", AnswerB: "Tenho dificuldade em tomar decisões"},
	{Id: 26, AnswerA: "Gosto de aprender coisas novas", AnswerB: "Na maioria das vezes tomo decisões por outros"},
	{Id: 27, AnswerA: "Gosto de fazer o trabalho o mais rápido possível", AnswerB: "Gosto de planejar com antecedência"},
	{Id: 28, AnswerA: "Gosto de agradar meus amigos", AnswerB: "Procuro sempre me esforçar ao máximo"},
	{Id: 29, AnswerA: "Gosto de movimentar-me", AnswerB: "Executo cada passo com muita cautela"},
	{Id: 30, AnswerA: "Gosto que me convidem", AnswerB: "Gosto de fazer uma coisa de cada vez"},
	{Id: 31, AnswerA: "Gosto de gente", AnswerB: "Agrada-me que cada coisa fique em seu lugar"},
	{Id: 32, AnswerA: "Sou rápido na execução de um trabalho", AnswerB: "Admiram minha paciência"},
	{Id: 33, AnswerA: "Normalmente gosto de trabalho árduo", AnswerB: "Consigo bons resultados com e através dos outros"},
	{Id: 34, AnswerA: "Gosto de pensar muito", AnswerB: "Não sou temperamental"},
	{Id: 35, AnswerA: "Sou minucioso no cumprimento das instruções", AnswerB: "Sempre controlo o trabalho dos outros"},
	{Id: 36, AnswerA: "Sempre respeito o meu superior", AnswerB: "Procuro fazer as coisas melhor do que os outros"},
	{Id: 37, AnswerA: "Agrada-me estudar o que fazer", AnswerB: "Sou muito ordenado"},
	{Id: 38, AnswerA: "Gosto de trabalhos que não exijam movimentação física", AnswerB: "Penso demais para tomar decisões"},
	{Id: 39, AnswerA: "Agrada-me ter amigos", AnswerB: "Prefiro trabalhar em equipe"},
	{Id: 40, AnswerA: "Normalmente estou bem disposto fisicamente", AnswerB: "Gosto de planejar o que faço"},
	{Id: 41, AnswerA: "Tenho muitos amigos", AnswerB: "Penso e planejo com antecedência"},
	{Id: 42, AnswerA: "Quando me ferem, eu retruco", AnswerB: "Dizem que não fico satisfeito até resolver um trabalho"},
	{Id: 43, AnswerA: "Agrada-me fazer pequenas coisas", AnswerB: "Gosto de organizar meu trabalho"},
	{Id: 44, AnswerA: "Dizem que me dou bem com todos", AnswerB: "Dizem que sou detalhista"},
	{Id: 45, AnswerA: "Executo meu trabalho com atenção minuciosa", AnswerB: "Sou muito controlado"},
	{Id: 46, AnswerA: "Sou trabalhador esforçado", AnswerB: "Arrisco-me com facilidade"},
	{Id: 47, AnswerA: "Consigo que as pessoas trabalhem intensamente", AnswerB: "Sinto-me bem no trabalho"},
	{Id: 48, AnswerA: "As pessoas sempre me seguem", AnswerB: "Geralmente falo rápido"},
	{Id: 49, AnswerA: "Sou rígido no cumprimento das normas", AnswerB: "Sempre tento ser o melhor"},
	{Id: 50, AnswerA: "Ajo com rapidez", AnswerB: "Sou cordial e atencioso"},
	{Id: 51, AnswerA: "Sou obediente", AnswerB: "Tudo que inicio, eu acabo"},
	{Id: 52, AnswerA: "Gosto de pensar muito para agir", AnswerB: "Gosto de trabalhar com detalhes"},
	{Id: 53, AnswerA: "Decido rápido", AnswerB: "Gosto de executar as coisas rapidamente"},
	{Id: 54, AnswerA: "Tenho dificuldade em fazer amigos", AnswerB: "Não gosto de trabalhos que exijam movimentação"},
	{Id: 55, AnswerA: "Dizem que sou criativo", AnswerB: "Agrada-me a execução de trabalhos que os outros não conseguiram fazer"},
	{Id: 56, AnswerA: "Sou muito esforçado", AnswerB: "Tenho muita paciência"},
	{Id: 57, AnswerA: "Gosto de conversar com o meu superior", AnswerB: "Dou muita importância às normas"},
	{Id: 58, AnswerA: "Agrada-me ter as coisas limpas e em ordem", AnswerB: "Dizem que tenho muita paciência"},
	{Id: 59, AnswerA: "Quando posso sou criativo", AnswerB: "Gosto de trabalhar em equipe"},
	{Id: 60, AnswerA: "Sou atencioso com as pessoas da minha equipe", AnswerB: "Desejo que as pessoas me levem em consideração"},
	{Id: 61, AnswerA: "Agrada-me trabalhos que outros não conseguiram fazer", AnswerB: "Gosto de acabar o que comecei"},
	{Id: 62, AnswerA: "Tenho muita paciência", AnswerB: "Tenho dificuldade de expressão, quando estou com raiva"},
	{Id: 63, AnswerA: "As pessoas me obedecem", AnswerB: "Sou minucioso"},
	{Id: 64, AnswerA: "Sempre sigo as ordens que me dão", AnswerB: "Eu não escondo minha irritação"},
	{Id: 65, AnswerA: "Sou muito obediente", AnswerB: "Sou muito franco"},
	{Id: 66, AnswerA: "Gosto de fazer um trabalho bem feito", AnswerB: "Gosto de movimentar-me"},
	{Id: 67, AnswerA: "Sinto-me realizado no trabalho", AnswerB: "Penso que sei liderar"},
	{Id: 68, AnswerA: "Agrada-me variar na execução dos meus trabalhos", AnswerB: "Sinto prazer em falar dos meus sucessos"},
	{Id: 69, AnswerA: "Sou rápido para executar um trabalho", AnswerB: "Meus colegas dizem que sou incansável"},
	{Id: 70, AnswerA: "Tenho facilidade de entrosamento", AnswerB: "Sou muito afetivo"},
	{Id: 71, AnswerA: "Prefiro mandar fazer", AnswerB: "Gosto de terminar o trabalho que comecei"},
	{Id: 72, AnswerA: "Gosto de despertar a atenção", AnswerB: "Agrada-me quando me pedem sugestões"},
	{Id: 73, AnswerA: "Sempre sigo as normas", AnswerB: "Tenho que concluir o que comecei"},
	{Id: 74, AnswerA: "Sempre sei onde está o que guardei", AnswerB: "Não gosto de pessoas rotineiras"},
	{Id: 75, AnswerA: "Gosto que me expliquem o que fazer", AnswerB: "Discuto muito pouco com meu superior"},
	{Id: 76, AnswerA: "Gosto de liderar", AnswerB: "Gosto de organizar meu trabalho"},
	{Id: 77, AnswerA: "Não sou de ficar calado quando me ferem", AnswerB: "Sinto-me bem fazendo parte da equipe"},
	{Id: 78, AnswerA: "Sempre acompanho o trabalho dos outros", AnswerB: "Tenho condições de decidir com rapidez"},
	{Id: 79, AnswerA: "Gosto quando são amistosos e íntimos comigo", AnswerB: "Agrada-me ser notado no grupo"},
	{Id: 80, AnswerA: "Sempre verifico o que os outros fazem", AnswerB: "Gosto de executar bem um trabalho difícil"},
	{Id: 81, AnswerA: "Movimento-me com facilidade", AnswerB: "Sempre verifico meus arquivos"},
	{Id: 82, AnswerA: "Arrisco-me com facilidade", AnswerB: "Gosto que cada coisa fique em seu lugar"},
	{Id: 83, AnswerA: "Nas situações difíceis penso melhor", AnswerB: "Prefiro trabalhos que exijam pouca movimentação"},
	{Id: 84, AnswerA: "Tenho dificuldade em terminar o que comecei", AnswerB: "Em grupo, sinto-me retraído"},
	{Id: 85, AnswerA: "Defendo sempre meu bom nome", AnswerB: "Fico satisfeito quando faço algo diferente"},
	{Id: 86, AnswerA: "Sou minucioso no cumprimento das normas", AnswerB: "Conto meus problemas íntimos aos amigos"},
	{Id: 87, AnswerA: "Gosto de instruções detalhadas sobre meu trabalho", AnswerB: "Não gosto de instruções detalhadas sobre meu trabalho"},
	{Id: 88, AnswerA: "Quando os outros estão errados sempre lhes digo", AnswerB: "Aborreço-me quando não gostam de mim"},
	{Id: 89, AnswerA: "Consigo bons resultados com e através dos outros", AnswerB: "Penso que tenho bom controle emocional"},
	{Id: 90, AnswerA: "Gosto de verificar tudo com muito cuidado", AnswerB: "Não gosto de planejar muito"},
	{Id: 91, AnswerA: "Gosto de estar com a equipe", AnswerB: "Assumo a responsabilidade por outros"},
	{Id: 92, AnswerA: "Sou atencioso com minha equipe", AnswerB: "Agrada-me ser bem sucedido"},
	{Id: 93, AnswerA: "Gosto de variedades no meu trabalho", AnswerB: "Gosto de atender aos meus amigos"},
	{Id: 94, AnswerA: "Aborreço-me com facilidade", AnswerB: "Sinto-me inseguro quando tomo certas decisões"},
	{Id: 95, AnswerA: "Sempre faço o que me mandam", AnswerB: "Sempre atendo aos meus amigos"},
	{Id: 96, AnswerA: "Sinto muita vontade de acabar o que comecei", AnswerB: "Não gosto de ficar à toa no trabalho"},
	{Id: 97, AnswerA: "Acato as sugestões das pessoas que gosto", AnswerB: "Desagrada-me o trabalho rotineiro"},
	{Id: 98, AnswerA: "Agrada-me Ter amigos mais chegados", AnswerB: "Sinto-me bem dando sugestões aos outros"},
	{Id: 99, AnswerA: "Sempre executo meu trabalho com muita dedicação", AnswerB: "Agradam-me os trabalhos que exijam detalhes"},
	{Id: 100, AnswerA: "Normalmente trabalho com intensidade", AnswerB: "Gosto de pensar e planejar antes de agir"},
}

var QuestionsCategoryMap = map[int64]Category{
	1:   {AnswerA: 7, AnswerB: 19},
	2:   {AnswerA: 10, AnswerB: 18},
	3:   {AnswerA: 4, AnswerB: 5},
	4:   {AnswerA: 12, AnswerB: 17},
	5:   {AnswerA: 6, AnswerB: 1},
	6:   {AnswerA: 13, AnswerB: 3},
	7:   {AnswerA: 8, AnswerB: 7},
	8:   {AnswerA: 16, AnswerB: 11},
	9:   {AnswerA: 17, AnswerB: 20},
	10:  {AnswerA: 19, AnswerB: 14},
	11:  {AnswerA: 5, AnswerB: 14},
	12:  {AnswerA: 8, AnswerB: 2},
	13:  {AnswerA: 15, AnswerB: 11},
	14:  {AnswerA: 6, AnswerB: 7},
	15:  {AnswerA: 13, AnswerB: 20},
	16:  {AnswerA: 4, AnswerB: 1},
	17:  {AnswerA: 12, AnswerB: 3},
	18:  {AnswerA: 9, AnswerB: 5},
	19:  {AnswerA: 10, AnswerB: 17},
	20:  {AnswerA: 17, AnswerB: 5},
	21:  {AnswerA: 9, AnswerB: 8},
	22:  {AnswerA: 12, AnswerB: 18},
	23:  {AnswerA: 4, AnswerB: 19},
	24:  {AnswerA: 13, AnswerB: 17},
	25:  {AnswerA: 6, AnswerB: 5},
	26:  {AnswerA: 15, AnswerB: 3},
	27:  {AnswerA: 8, AnswerB: 1},
	28:  {AnswerA: 16, AnswerB: 20},
	29:  {AnswerA: 19, AnswerB: 1},
	30:  {AnswerA: 18, AnswerB: 11},
	31:  {AnswerA: 5, AnswerB: 2},
	32:  {AnswerA: 8, AnswerB: 14},
	33:  {AnswerA: 9, AnswerB: 4},
	34:  {AnswerA: 1, AnswerB: 14},
	35:  {AnswerA: 10, AnswerB: 3},
	36:  {AnswerA: 12, AnswerB: 20},
	37:  {AnswerA: 1, AnswerB: 2},
	38:  {AnswerA: 6, AnswerB: 19},
	39:  {AnswerA: 16, AnswerB: 18},
	40:  {AnswerA: 19, AnswerB: 1},
	41:  {AnswerA: 5, AnswerB: 1},
	42:  {AnswerA: 13, AnswerB: 11},
	43:  {AnswerA: 7, AnswerB: 2},
	44:  {AnswerA: 5, AnswerB: 7},
	45:  {AnswerA: 7, AnswerB: 14},
	46:  {AnswerA: 9, AnswerB: 6},
	47:  {AnswerA: 4, AnswerB: 20},
	48:  {AnswerA: 4, AnswerB: 8},
	49:  {AnswerA: 10, AnswerB: 20},
	50:  {AnswerA: 8, AnswerB: 5},
	51:  {AnswerA: 12, AnswerB: 11},
	52:  {AnswerA: 1, AnswerB: 7},
	53:  {AnswerA: 6, AnswerB: 8},
	54:  {AnswerA: 19, AnswerB: 5},
	55:  {AnswerA: 15, AnswerB: 20},
	56:  {AnswerA: 9, AnswerB: 14},
	57:  {AnswerA: 12, AnswerB: 10},
	58:  {AnswerA: 2, AnswerB: 14},
	59:  {AnswerA: 15, AnswerB: 18},
	60:  {AnswerA: 17, AnswerB: 18},
	61:  {AnswerA: 20, AnswerB: 11},
	62:  {AnswerA: 14, AnswerB: 13},
	63:  {AnswerA: 4, AnswerB: 7},
	64:  {AnswerA: 10, AnswerB: 13},
	65:  {AnswerA: 12, AnswerB: 13},
	66:  {AnswerA: 7, AnswerB: 19},
	67:  {AnswerA: 9, AnswerB: 4},
	68:  {AnswerA: 15, AnswerB: 17},
	69:  {AnswerA: 8, AnswerB: 9},
	70:  {AnswerA: 18, AnswerB: 16},
	71:  {AnswerA: 3, AnswerB: 11},
	72:  {AnswerA: 17, AnswerB: 3},
	73:  {AnswerA: 10, AnswerB: 11},
	74:  {AnswerA: 2, AnswerB: 15},
	75:  {AnswerA: 10, AnswerB: 12},
	76:  {AnswerA: 4, AnswerB: 2},
	77:  {AnswerA: 13, AnswerB: 18},
	78:  {AnswerA: 3, AnswerB: 6},
	79:  {AnswerA: 16, AnswerB: 17},
	80:  {AnswerA: 3, AnswerB: 20},
	81:  {AnswerA: 19, AnswerB: 2},
	82:  {AnswerA: 6, AnswerB: 2},
	83:  {AnswerA: 19, AnswerB: 6},
	84:  {AnswerA: 17, AnswerB: 11},
	85:  {AnswerA: 13, AnswerB: 15},
	86:  {AnswerA: 10, AnswerB: 16},
	87:  {AnswerA: 10, AnswerB: 15},
	88:  {AnswerA: 13, AnswerB: 16},
	89:  {AnswerA: 4, AnswerB: 14},
	90:  {AnswerA: 2, AnswerB: 8},
	91:  {AnswerA: 18, AnswerB: 3},
	92:  {AnswerA: 18, AnswerB: 20},
	93:  {AnswerA: 15, AnswerB: 16},
	94:  {AnswerA: 6, AnswerB: 14},
	95:  {AnswerA: 12, AnswerB: 16},
	96:  {AnswerA: 11, AnswerB: 9},
	97:  {AnswerA: 12, AnswerB: 15},
	98:  {AnswerA: 16, AnswerB: 3},
	99:  {AnswerA: 9, AnswerB: 7},
	100: {AnswerA: 9, AnswerB: 1},
}

var ResultCellLocation = map[int64]string{
	1:  "C25",
	2:  "C24",
	3:  "C29",
	4:  "C31",
	5:  "C10",
	6:  "C23",
	7:  "C30",
	8:  "C27",
	9:  "C15",
	10: "C12",
	11: "C26",
	12: "C32",
	13: "C9",
	14: "C20",
	15: "C11",
	16: "C18",
	17: "C19",
	18: "C21",
	19: "C14",
	20: "C16",
}

var ResultScore = map[int64]map[int64]string{
	1: {
		0:  "Pessoa com Perfil Prático e Focado em Execução: Apresenta um pensamento concreto e uma postura prática, demonstrando grande habilidade para executar tarefas. No entanto, pode enfrentar dificuldades por falta de planejamento prévio. Realiza um trabalho eficiente em contextos onde os planos já estão definidos, preferindo atuar exclusivamente como executante.",
		1:  "Pessoa com Forte Tendência à Execução, mas com Falhas de Planejamento: Demonstra inclinação significativa para a execução de tarefas, sustentada por um pensamento concreto e prático. Gosta de atuar diretamente, mas pode perder-se em situações que requerem planejamento estratégico, comprometendo o alcance de resultados a longo prazo.",
		2:  "Pessoa com Forte Tendência à Execução, mas com Falhas de Planejamento: Demonstra inclinação significativa para a execução de tarefas, sustentada por um pensamento concreto e prático. Gosta de atuar diretamente, mas pode perder-se em situações que requerem planejamento estratégico, comprometendo o alcance de resultados a longo prazo.",
		3:  "Pessoa em Transição para um Perfil de Equilíbrio entre Execução e Planejamento: Começa a apresentar um maior equilíbrio entre as ações práticas e a definição de estratégias, embora ainda demonstre uma tendência à praticidade. Gosta de executar, mas já mostra sinais de evolução no desenvolvimento de competências de planejamento.",
		4:  "Pessoa com Interesse em Planejamento, mas com Foco em Praticidade: Apresenta capacidade inicial para planejar e organizar, embora demonstre maior interesse por atividades práticas. Essa pessoa parece estar em um processo de desenvolvimento de sua habilidade de planejamento, mantendo um perfil pragmático e orientado para a execução.",
		5:  "Pessoa com Boa Capacidade de Análise Lógica e Realismo: Demonstra habilidade para realizar análises lógicas e manter uma visão realista das situações. Planeja de forma eficiente e consegue implementar ideias na prática, evidenciando uma capacidade sólida de atingir as metas que estabelece.",
		6:  "Pessoa com Boa Capacidade de Análise Lógica e Realismo: Demonstra habilidade para realizar análises lógicas e manter uma visão realista das situações. Planeja de forma eficiente e consegue implementar ideias na prática, evidenciando uma capacidade sólida de atingir as metas que estabelece.",
		7:  "Pessoa com Tendência ao Planejamento em Detrimento da Execução: Apresenta um equilíbrio moderado entre planejamento e execução, com uma inclinação maior para a teorização e organização de ideias. Seu interesse está mais voltado ao planejamento estratégico do que à implementação prática, o que pode resultar em frustração, especialmente quando as metas estabelecidas não são plenamente alcançadas.",
		8:  "Pessoa com Foco Excessivo no Planejamento e Dificuldade na Execução: Destaca-se por seu pensamento teórico e abordagem analítica, priorizando o planejamento detalhado em relação à execução prática. Essa tendência de planejar em excesso pode dificultar o progresso na concretização de suas metas, gerando sentimentos de insatisfação ou frustração.",
		9:  "Pessoa com Foco Excessivo no Planejamento e Dificuldade na Execução: Destaca-se por seu pensamento teórico e abordagem analítica, priorizando o planejamento detalhado em relação à execução prática. Essa tendência de planejar em excesso pode dificultar o progresso na concretização de suas metas, gerando sentimentos de insatisfação ou frustração.",
		10: "Perfil de Pessoa com Excesso de Planejamento e Falta de Praticidade: Trata-se de um indivíduo com uma abordagem altamente lógica e voltada para a teorização. Dedica grande parte do seu tempo à idealização de conceitos e estratégias, mas enfrenta dificuldades significativas em transformar essas ideias em ações práticas. Essa inclinação ao planejamento excessivo pode comprometer a concretização de suas iniciativas, resultando na falta de resultados tangíveis.",
	},
	2: {
		0:  "Pessoa com Baixa Necessidade de Organização: Um indivíduo que não atribui grande importância à ordem ou à estruturação das coisas, adotando uma postura desorganizada. Confia na sua boa memória para registrar informações importantes, mas essa confiança excessiva pode levar a falhas no acompanhamento de tarefas e compromissos.",
		1:  "Pessoa com Baixa Necessidade de Organização: Um indivíduo que não atribui grande importância à ordem ou à estruturação das coisas, adotando uma postura desorganizada. Confia na sua boa memória para registrar informações importantes, mas essa confiança excessiva pode levar a falhas no acompanhamento de tarefas e compromissos.",
		2:  "Pessoa Desorganizada com Dificuldade em Métodos Sistemáticos: Demonstra pouca preocupação com a organização, revelando dificuldade em manter uma estrutura ordenada. Depende fortemente de sua memória para gerenciar informações, mas apresenta desafios em usar ferramentas como agendas e anotações, o que compromete sua eficiência.",
		3:  "Pessoa com Alguma Capacidade Organizativa e Esforço de Melhoria: Possui uma habilidade organizativa inicial, mas tende à desorganização. Confia em sua memória para lidar com tarefas e informações, mas está visivelmente se empenhando em aprimorar sua capacidade de organização.",
		4:  "Pessoa em Evolução Organizativa: Alguém que desenvolveu uma boa capacidade de organização ao longo do tempo, superando características de desorganização no passado. Foca em uma visão ampla e estratégica, sem se deixar prender a detalhes insignificantes.",
		5:  "Pessoa com Boa Capacidade Organizativa e Pragmática: Demonstra habilidades organizativas sólidas, mantendo as coisas em ordem sem exageros. Prioriza uma visão macro das situações, evitando se envolver em detalhes irrelevantes e equilibrando praticidade com eficiência.",
		6:  "Pessoa Organizada em Busca de Aperfeiçoamento: Apresenta uma abordagem organizada e estruturada, resultado de uma evolução contínua. Embora já tenha superado características perfeccionistas, ainda se exige bastante e tende a esperar o mesmo das pessoas ao seu redor.",
		7:  "Pessoa Rígida e Perfeccionista na Organização: Um indivíduo meticuloso, que adota um estilo organizativo obstinado e, por vezes, inflexível. Possui traços claros de perfeccionismo e exige altos padrões tanto de si mesmo quanto das pessoas mais próximas.",
		8:  "Pessoa com Necessidade Excessiva de Organização: Um perfil que investe tempo exagerado na organização, muitas vezes se preocupando com detalhes irrelevantes. Essa obsessão pode levar à perda de produtividade e dificuldade em delegar tarefas, comprometendo sua eficiência geral.",
		9:  "Pessoa com Necessidade Excessiva de Organização: Um perfil que investe tempo exagerado na organização, muitas vezes se preocupando com detalhes irrelevantes. Essa obsessão pode levar à perda de produtividade e dificuldade em delegar tarefas, comprometendo sua eficiência geral.",
		10: "Pessoa com Necessidade Excessiva de Organização: Um perfil que investe tempo exagerado na organização, muitas vezes se preocupando com detalhes irrelevantes. Essa obsessão pode levar à perda de produtividade e dificuldade em delegar tarefas, comprometendo sua eficiência geral.",
	},
	3: {
		0:  "Pessoa com Baixa Propensão para Acompanhamento e Supervisão: Um indivíduo que demonstra pouca necessidade de acompanhar ou supervisionar o trabalho alheio. Evita qualquer situação em que possa parecer “cobrador”, devido ao desconforto de sentir-se cobrado por outros. Essa postura pode limitar sua capacidade de liderar com eficácia, especialmente em contextos que demandam supervisão ativa.",
		1:  "Pessoa com Baixa Propensão para Acompanhamento e Supervisão: Um indivíduo que demonstra pouca necessidade de acompanhar ou supervisionar o trabalho alheio. Evita qualquer situação em que possa parecer “cobrador”, devido ao desconforto de sentir-se cobrado por outros. Essa postura pode limitar sua capacidade de liderar com eficácia, especialmente em contextos que demandam supervisão ativa.",
		2:  "Pessoa com Baixa Propensão para Acompanhamento e Supervisão: Um indivíduo que demonstra pouca necessidade de acompanhar ou supervisionar o trabalho alheio. Evita qualquer situação em que possa parecer “cobrador”, devido ao desconforto de sentir-se cobrado por outros. Essa postura pode limitar sua capacidade de liderar com eficácia, especialmente em contextos que demandam supervisão ativa.",
		3:  "Pessoa Focada na Execução, mas com Pouca Interação Direta com a Equipe: Prefere concentrar-se na execução de suas próprias responsabilidades, sem investir tempo no acompanhamento ou orientação direta de sua equipe. Mostra-se aberta a receber feedback e acompanhamento sobre seu próprio trabalho, o que pode ser natural em funções predominantemente técnicas ou de assessoria, onde a execução prática é priorizada.",
		4:  "Pessoa Focada na Execução, mas com Pouca Interação Direta com a Equipe: Prefere concentrar-se na execução de suas próprias responsabilidades, sem investir tempo no acompanhamento ou orientação direta de sua equipe. Mostra-se aberta a receber feedback e acompanhamento sobre seu próprio trabalho, o que pode ser natural em funções predominantemente técnicas ou de assessoria, onde a execução prática é priorizada.",
		5:  "Pessoa com Habilidade Crescente em Supervisão e Desenvolvimento de Equipe: Demonstra uma necessidade emergente de acompanhar e supervisionar as atividades realizadas por outros. Mostra-se capaz de promover o crescimento e o desenvolvimento de sua equipe, incentivando ativamente o aprimoramento das habilidades individuais e o alcance de resultados coletivos mais eficazes.",
		6:  "Pessoa com Habilidade em Acompanhamento e Desenvolvimento de Equipe: Consegue realizar um acompanhamento eficaz e assertivo do trabalho dos outros, oferecendo orientação e suporte sempre que necessário. Mostra habilidade para ajudar membros da equipe com baixo desempenho, promovendo seu desenvolvimento profissional. Essa pessoa é competente em transformar iniciantes em profissionais qualificados, mantendo supervisão regular sobre tarefas e projetos, mas pode apresentar baixa flexibilidade ao aderir a um controle mais rígido.",
		7:  "Pessoa com Habilidade em Acompanhamento e Desenvolvimento de Equipe: Consegue realizar um acompanhamento eficaz e assertivo do trabalho dos outros, oferecendo orientação e suporte sempre que necessário. Mostra habilidade para ajudar membros da equipe com baixo desempenho, promovendo seu desenvolvimento profissional. Essa pessoa é competente em transformar iniciantes em profissionais qualificados, mantendo supervisão regular sobre tarefas e projetos, mas pode apresentar baixa flexibilidade ao aderir a um controle mais rígido.",
		8:  "Pessoa que pratica um acompanhamento frequente de tarefas e projetos, exercendo um forte controle sobre a evolução das atividades. É menos flexível em sua abordagem, preferindo manter um alto grau de controle para garantir que tudo esteja em conformidade com suas expectativas.",
		9:  "Pessoa com Postura Agressiva Diante de Conflitos: Adota uma abordagem inflexível e pouco sensível ao resolver problemas, impondo-se de maneira agressiva em situações de conflito. Demonstra pouca abertura para o diálogo e mediação, preferindo métodos diretos e autoritários, o que pode dificultar um ambiente colaborativo.",
		10: "Pessoa com Controle Rígido e Estilo Autocrático de Liderança: Exerce um alto nível de controle sobre todos os aspectos do trabalho, sendo extremamente detalhista e pouco inclinado a delegar tarefas. Tende a aplicar punições de forma imediata quando percebe desvios ou desobediências, adotando um perfil de chefia autoritário que centraliza as decisões, sem promover autonomia ou participação ativa da equipe.",
	},
	4: {
		0:  "Pessoa que enfrenta grande dificuldade em assumir responsabilidades de liderança. Prefere concentrar seus esforços na execução de tarefas, confiando mais na qualidade de seu próprio trabalho do que no dos outros. Essa característica pode estar associada a uma atenção excessiva aos detalhes e/ou traços de perfeccionismo, sendo um comportamento compreensível em funções técnicas ou de assessoria.",
		1:  "Pessoa que enfrenta grande dificuldade em assumir responsabilidades de liderança. Prefere concentrar seus esforços na execução de tarefas, confiando mais na qualidade de seu próprio trabalho do que no dos outros. Essa característica pode estar associada a uma atenção excessiva aos detalhes e/ou traços de perfeccionismo, sendo um comportamento compreensível em funções técnicas ou de assessoria.",
		2:  "Pessoa que enfrenta grande dificuldade em assumir responsabilidades de liderança. Prefere concentrar seus esforços na execução de tarefas, confiando mais na qualidade de seu próprio trabalho do que no dos outros. Essa característica pode estar associada a uma atenção excessiva aos detalhes e/ou traços de perfeccionismo, sendo um comportamento compreensível em funções técnicas ou de assessoria.",
		3:  "Pessoa que encontra desafios ao assumir o papel de líder, demonstrando impaciência para ensinar ou delegar tarefas. Prefere realizar atividades por conta própria, devido à confiança na sua execução. Provavelmente possui um perfil detalhista e/ou perfeccionista, o que torna essa postura mais adequada em funções técnicas ou consultivas.",
		4:  "Pessoa que encontra desafios ao assumir o papel de líder, demonstrando impaciência para ensinar ou delegar tarefas. Prefere realizar atividades por conta própria, devido à confiança na sua execução. Provavelmente possui um perfil detalhista e/ou perfeccionista, o que torna essa postura mais adequada em funções técnicas ou consultivas.",
		5:  "Pessoa com inclinação crescente para a liderança, capaz de inspirar e motivar sua equipe a alcançar objetivos estabelecidos. Contribui para a criação de um ambiente de trabalho harmonioso e colaborativo, embora ainda prefira, ocasionalmente, executar tarefas diretamente em vez de apenas delegá-las.",
		6:  "Pessoa que demonstra sólidas habilidades de liderança, conseguindo motivar e unir sua equipe na busca por resultados. Tem capacidade de inspirar confiança no grupo e promove um ambiente de sinergia, onde os membros se sentem seguros e engajados para contribuir com o sucesso coletivo.",
		7:  "Pessoa que demonstra sólidas habilidades de liderança, conseguindo motivar e unir sua equipe na busca por resultados. Tem capacidade de inspirar confiança no grupo e promove um ambiente de sinergia, onde os membros se sentem seguros e engajados para contribuir com o sucesso coletivo.",
		8:  "Pessoa com forte habilidade de liderança, mas que pode se preocupar excessivamente em provar sua competência nesse papel. Apesar disso, consegue engajar e motivar sua equipe, criando um ambiente de colaboração e harmonia que favorece o alcance de metas e resultados esperados.",
		9:  "Pessoa extremamente confiante em seu papel como líder, preocupando-se em reforçar constantemente sua imagem diante do grupo. Essa abordagem pode, em algumas situações, impactar negativamente a liderança, pois tende a centralizar as responsabilidades. Ainda assim, promove um ambiente de sinergia que mantém a equipe motivada e unida.",
		10: "Pessoa que, apesar de sua facilidade para liderar, demonstra preocupação excessiva em concentrar a autoridade em si mesma. Essa atitude pode prejudicar sua liderança, uma vez que todos os problemas passam a ser direcionados para ela, gerando dependência do grupo em relação a sua figura, em vez de na organização como um todo. No entanto, consegue cultivar um clima de colaboração e engajamento entre os membros da equipe.",
	},
	5: {
		0:  "Pessoa com Dificuldade em Expressar suas Ideias de Forma Clara: Demonstra grande dificuldade em comunicar de maneira eficaz o que deseja transmitir. Adota uma abordagem excessivamente sintética e concisa em suas interações, limitando o detalhamento necessário para facilitar o entendimento. Mostra pouca necessidade de verbalizar seus pensamentos, partindo do pressuposto de que os outros compreenderão intuitivamente suas ideias, o que pode gerar confusões e mal-entendidos.",
		1:  "Pessoa com Dificuldade em Expressar suas Ideias de Forma Clara: Demonstra grande dificuldade em comunicar de maneira eficaz o que deseja transmitir. Adota uma abordagem excessivamente sintética e concisa em suas interações, limitando o detalhamento necessário para facilitar o entendimento. Mostra pouca necessidade de verbalizar seus pensamentos, partindo do pressuposto de que os outros compreenderão intuitivamente suas ideias, o que pode gerar confusões e mal-entendidos.",
		2:  "Pessoa com Dificuldade em Expressar suas Ideias de Forma Clara: Demonstra grande dificuldade em comunicar de maneira eficaz o que deseja transmitir. Adota uma abordagem excessivamente sintética e concisa em suas interações, limitando o detalhamento necessário para facilitar o entendimento. Mostra pouca necessidade de verbalizar seus pensamentos, partindo do pressuposto de que os outros compreenderão intuitivamente suas ideias, o que pode gerar confusões e mal-entendidos.",
		3:  "Pessoa com Comunicação Sintética e Concisa: Apresenta dificuldade em transmitir suas ideias de forma clara e completa devido a uma comunicação excessivamente breve. Resume o que precisa ser dito com poucas palavras, mesmo quando a situação exige maior detalhamento, o que pode gerar falhas no entendimento.",
		4:  "Pessoa com Comunicação Limitada e Foco na Síntese: Ainda encontra desafios para se expressar de forma clara e objetiva, preferindo ser sintética ao transmitir mensagens. Essa abordagem pode resultar em informações insuficientes, comprometendo a clareza e a eficácia da comunicação.",
		5:  "Pessoa com Comunicação Clara e Objetiva: Demonstra habilidade para transmitir suas ideias de forma precisa, reduzindo possíveis ambiguidades ou mal-entendidos. Mantém o grupo informado sobre pensamentos, opiniões e sentimentos, promovendo um fluxo de comunicação eficaz e transparente.",
		6:  "Pessoa com Comunicação Clara e Orientada ao Grupo: Possui uma comunicação assertiva e objetiva, conseguindo manter as pessoas ao seu redor bem informadas. Essa habilidade minimiza ruídos na comunicação e fortalece a coesão e o alinhamento dentro do grupo.",
		7:  "Pessoa com Tendência à Prolixidade na Expressão: Apresenta habilidade de comunicação, mas com uma inclinação à prolixidade. Tem necessidade de detalhar excessivamente para garantir que seja bem compreendida pelos outros, o que pode estar relacionado a traços de perfeccionismo.",
		8:  "Pessoa com Forte Tendência à Prolixidade e Busca por Clareza: Demonstra uma inclinação marcante para a prolixidade, sentindo a necessidade de oferecer explicações detalhadas e extensas para garantir que suas ideias sejam plenamente compreendidas. Essa característica parece estar ligada a um desejo de perfeição, levando-a a preocupar-se em explicar cada aspecto minuciosamente, na tentativa de evitar mal-entendidos e ser completamente clara.",
		9:  "Pessoa com Forte Tendência à Prolixidade e Busca por Clareza: Demonstra uma inclinação marcante para a prolixidade, sentindo a necessidade de oferecer explicações detalhadas e extensas para garantir que suas ideias sejam plenamente compreendidas. Essa característica parece estar ligada a um desejo de perfeição, levando-a a preocupar-se em explicar cada aspecto minuciosamente, na tentativa de evitar mal-entendidos e ser completamente clara.",
		10: "Pessoa com Forte Necessidade de Clareza e Aceitação Social: Demonstra uma necessidade excessiva de explicitar detalhadamente tudo o que deseja comunicar, buscando garantir o máximo de compreensão por parte dos outros. Esse comportamento reflete um esforço contínuo por perfeição, motivado pelo desejo de ser plenamente aceito pelo grupo com o qual convive. Contudo, essa característica resulta em um discurso prolixo, com explicações frequentemente mais extensas do que o necessário.",
	},
	6: {
		0:  "Pessoa que demonstra dificuldades em tomar decisões, principalmente devido à sua tendência a analisar e ponderar excessivamente. Prefere situações rotineiras e familiares, onde pode aplicar soluções conhecidas, sentindo-se mais confortável em executar o que já domina.",
		1:  "Pessoa que demonstra dificuldades em tomar decisões, principalmente devido à sua tendência a analisar e ponderar excessivamente. Prefere situações rotineiras e familiares, onde pode aplicar soluções conhecidas, sentindo-se mais confortável em executar o que já domina.",
		2:  "Pessoa que enfrenta certa dificuldade em tomar decisões devido à sua tendência de analisar excessivamente as opções. Essa característica pode levá-la, em alguns casos, a evitar se posicionar ou a adiar decisões importantes. Quando se depara com situações fora da rotina, tende a agir de forma mais lenta, mostrando uma necessidade maior de tempo para refletir e se adaptar antes de escolher um caminho.",
		3:  "Pessoa que enfrenta certa dificuldade em tomar decisões devido à sua tendência de analisar excessivamente as opções. Essa característica pode levá-la, em alguns casos, a evitar se posicionar ou a adiar decisões importantes. Quando se depara com situações fora da rotina, tende a agir de forma mais lenta, mostrando uma necessidade maior de tempo para refletir e se adaptar antes de escolher um caminho.",
		4:  "Pessoa que enfrenta certa dificuldade em tomar decisões devido à sua tendência de analisar excessivamente as opções. Essa característica pode levá-la, em alguns casos, a evitar se posicionar ou a adiar decisões importantes. Quando se depara com situações fora da rotina, tende a agir de forma mais lenta, mostrando uma necessidade maior de tempo para refletir e se adaptar antes de escolher um caminho.",
		5:  "Pessoa que, embora enfrente desafios ocasionais ao decidir, consegue lidar bem com questões de rotina. Sua hesitação está mais ligada a contextos que demandam maior análise de riscos ou envolvem situações fora de sua zona de conforto.",
		6:  "Pessoa que demonstra facilidade em tomar decisões de maneira rápida e assertiva. Avalia cuidadosamente os riscos antes de agir, garantindo que suas escolhas sejam bem fundamentadas e no momento oportuno. Essa habilidade destaca-se como um ponto forte em sua capacidade de liderança e execução.",
		7:  "Pessoa que demonstra facilidade em tomar decisões de maneira rápida e assertiva. Avalia cuidadosamente os riscos antes de agir, garantindo que suas escolhas sejam bem fundamentadas e no momento oportuno. Essa habilidade destaca-se como um ponto forte em sua capacidade de liderança e execução.",
		8:  "Pessoa com agilidade para tomar decisões, mas que ocasionalmente pode agir com precipitação. Ao priorizar a rapidez, pode assumir riscos desnecessários, o que impacta a qualidade dos resultados. Além disso, sua expectativa por velocidade pode gerar pressão sobre os outros.",
		9:  "Pessoa que toma decisões extremamente rápido, muitas vezes sem avaliar adequadamente os riscos envolvidos. Focada em velocidade, demonstra uma preocupação excessiva em exigir o mesmo ritmo dos outros, o que pode prejudicar tanto os resultados quanto a dinâmica do grupo.",
		10: "Pessoa que toma decisões extremamente rápido, muitas vezes sem avaliar adequadamente os riscos envolvidos. Focada em velocidade, demonstra uma preocupação excessiva em exigir o mesmo ritmo dos outros, o que pode prejudicar tanto os resultados quanto a dinâmica do grupo.",
	},
	8: {
		0:  "Pessoa que demonstra dificuldade em realizar tarefas sob pressão de tempo, preferindo prazos mais longos para executar suas atividades. Sua tendência ao perfeccionismo faz com que dedique mais tempo à qualidade do trabalho, mesmo que isso possa comprometer o cumprimento de prazos estabelecidos, gerando certo nível de estresse.",
		1:  "Pessoa que demonstra dificuldade em realizar tarefas sob pressão de tempo, preferindo prazos mais longos para executar suas atividades. Sua tendência ao perfeccionismo faz com que dedique mais tempo à qualidade do trabalho, mesmo que isso possa comprometer o cumprimento de prazos estabelecidos, gerando certo nível de estresse.",
		2:  "Pessoa que possui baixa capacidade para realizar tarefas sob pressão de tempo e prefere prazos mais extensos para garantir a qualidade de seu trabalho. Seu perfil perfeccionista a leva a focar nos detalhes, o que, embora contribua para resultados bem feitos, pode causar estresse em situações com demandas urgentes.",
		3:  "Pessoa que, apesar de conseguir trabalhar sob pressão e com prazos curtos, prefere prazos mais longos para desempenhar suas tarefas de maneira satisfatória. Sua inclinação ao perfeccionismo faz com que busque sempre entregar o melhor, mas essa característica pode gerar estresse ao lidar com prazos apertados.",
		4:  "Pessoa que demonstra esforço para se adaptar a tarefas com prazos curtos e sob pressão, ainda que prefira prazos mais amplos. Está em um processo de aprendizado para lidar melhor com situações de alta demanda, buscando alcançar suas metas sem comprometer seu bem-estar emocional.",
		5:  "Pessoa que gerencia seu tempo de forma eficiente, concluindo as tarefas dentro dos prazos estabelecidos. Tem facilidade para lidar com demandas sob pressão, sem apresentar sinais de estresse, o que demonstra uma notável adaptabilidade aos ritmos acelerados do mundo atual.",
		6:  "Pessoa que gerencia seu tempo de forma eficiente, concluindo as tarefas dentro dos prazos estabelecidos. Tem facilidade para lidar com demandas sob pressão, sem apresentar sinais de estresse, o que demonstra uma notável adaptabilidade aos ritmos acelerados do mundo atual.",
		7:  "Pessoa que gerencia seu tempo de forma eficiente, concluindo as tarefas dentro dos prazos estabelecidos. Tem facilidade para lidar com demandas sob pressão, sem apresentar sinais de estresse, o que demonstra uma notável adaptabilidade aos ritmos acelerados do mundo atual.",
		8:  "Pessoa que se destaca pela capacidade de executar tarefas de maneira ágil, mesmo em situações com alta pressão de tempo. Sua habilidade em equilibrar velocidade e qualidade permite que entregue resultados consistentes e satisfatórios, mesmo em cenários desafiadores.",
		9:  "Pessoa ágil e determinada a cumprir prazos, priorizando entregas rápidas sem comprometer a qualidade. Não aprecia cobranças, mas seu dinamismo e eficiência fazem com que se destaque em ambientes de alta demanda.",
		10: "Pessoa extremamente acelerada na entrega de resultados, mas cuja rapidez pode, ocasionalmente, prejudicar a qualidade do trabalho. Mostra impaciência tanto com processos lentos quanto com o ritmo de outras pessoas, além de apresentar aversão ao controle externo sobre seu desempenho.",
	},
	9: {
		0:  "Pessoa que evita assumir responsabilidades, preferindo delegar tarefas aos demais. Não se sente atraída por trabalhos intensos ou desafiadores, apresentando baixo comprometimento com as atividades que requerem esforço contínuo.",
		1:  "Pessoa que evita assumir responsabilidades, preferindo delegar tarefas aos demais. Não se sente atraída por trabalhos intensos ou desafiadores, apresentando baixo comprometimento com as atividades que requerem esforço contínuo.",
		2:  "Pessoa que tende a assumir poucas responsabilidades, frequentemente delegando tarefas para outros. Mostra baixa afinidade com trabalhos que demandam esforço intenso e pode não se sentir plenamente envolvida ou engajada em suas atividades.",
		3:  "Pessoa que demonstra certa afinidade com trabalhos árduos e intensos, mostrando disposição para se dedicar a tarefas desafiadoras. Consegue alcançar resultados satisfatórios, atingindo algumas de suas metas, e valoriza o reconhecimento por seus esforços, o que contribui para sua motivação e senso de realização.",
		4:  "Pessoa que mantém um bom equilíbrio em relação à carga de trabalho, demonstrando responsabilidade e comprometimento. Responde de maneira eficiente às demandas que enfrenta, sem apresentar sinais de sobrecarga ou desmotivação.",
		5:  "Pessoa que mantém um bom equilíbrio em relação à carga de trabalho, demonstrando responsabilidade e comprometimento. Responde de maneira eficiente às demandas que enfrenta, sem apresentar sinais de sobrecarga ou desmotivação.",
		6:  "Pessoa que demonstra uma excelente capacidade de lidar com a carga de trabalho, respondendo de forma eficiente às demandas exigidas. No entanto, ao selecionar tarefas, tende a assumir uma quantidade elevada de atividades e responsabilidades, o que pode levar a um excesso de trabalho. Essa característica, embora reflita comprometimento e produtividade, pode representar um risco de sobrecarga se não for bem administrada.",
		7:  "Pessoa que se destaca por sua capacidade de lidar com altas demandas de trabalho. Assume com facilidade tarefas adicionais e responsabilidades extras, embora, em alguns casos, isso possa levar ao risco de sobrecarga ou exaustão física.",
		8:  "Pessoa que se destaca por sua capacidade de lidar com altas demandas de trabalho. Assume com facilidade tarefas adicionais e responsabilidades extras, embora, em alguns casos, isso possa levar ao risco de sobrecarga ou exaustão física.",
		9:  "Pessoa que busca reconhecimento pelo seu esforço e dedicação, assumindo uma grande quantidade de tarefas e mantendo um alto nível de produtividade. No entanto, essa postura pode levá-la a exceder seus limites, aumentando o risco de desgaste físico e mental devido à sobrecarga de trabalho.",
		10: "Pessoa que busca reconhecimento pelo seu esforço e dedicação, assumindo uma grande quantidade de tarefas e mantendo um alto nível de produtividade. No entanto, essa postura pode levá-la a exceder seus limites, aumentando o risco de desgaste físico e mental devido à sobrecarga de trabalho.",
	},
	12: {
		0:  "Perfil de Pessoa Independente e Crítica: Trata-se de alguém que prefere trabalhar sem a influência direta de figuras de autoridade. Essa pessoa demonstra autossuficiência, pensamento crítico e coragem para assumir riscos. No entanto, essa postura pode levá-la a contestar ou opor-se de forma precoce à autoridade, o que dificulta a construção de uma relação colaborativa com o chefe. Há um receio em ser visto como puxa-saco, que acaba limitando seu potencial de crescimento e causando perdas significativas em termos de alianças profissionais.",
		1:  "Perfil de Pessoa Independente e Crítica: Trata-se de alguém que prefere trabalhar sem a influência direta de figuras de autoridade. Essa pessoa demonstra autossuficiência, pensamento crítico e coragem para assumir riscos. No entanto, essa postura pode levá-la a contestar ou opor-se de forma precoce à autoridade, o que dificulta a construção de uma relação colaborativa com o chefe. Há um receio em ser visto como puxa-saco, que acaba limitando seu potencial de crescimento e causando perdas significativas em termos de alianças profissionais.",
		2:  "Perfil de Pessoa Exigente e Oposta à Autoridade: Essa pessoa valoriza a competência e prefere um ambiente de trabalho livre de estímulos constantes ou interferências superiores. Ainda assim, tende a antecipar conflitos e oposições com figuras de autoridade, o que pode impactar negativamente sua capacidade de alavancar parcerias estratégicas. O receio de ser percebida como submissa impede que construa uma relação de apoio mútuo com o chefe, levando à perda de oportunidades importantes.",
		3:  "Perfil de Pessoa com Dificuldade em Alianças Hierárquicas: Apresenta desafios em estabelecer uma relação de parceria ou aliança com figuras de autoridade. Essa dificuldade é alimentada pelo temor de ser rotulada como “puxa-saco”, o que limita sua capacidade de aproveitar os benefícios de uma colaboração mais próxima com o chefe, resultando em desvantagens no ambiente profissional.",
		4:  "Perfil de Pessoa Transparente e Colaborativa: Um indivíduo que já desenvolveu uma boa relação com figuras de chefia, transformando o chefe em um aliado estratégico. Embora tenha sido mais autossuficiente no passado, agora demonstra preocupação em construir um relacionamento baseado na transparência e na confiança. Essa evolução favorece tanto o desempenho individual quanto o alinhamento com objetivos organizacionais.",
		5:  "Perfil de Pessoa Colaborativa e Estratégica: Alguém que consegue estabelecer uma relação sólida e positiva com figuras de autoridade, apresentando-se como um bom negociador e sabendo contestar ou se opor quando necessário. Essa pessoa tem a habilidade de transformar seu chefe em um aliado, construindo uma parceria baseada em confiança e respeito mútuo.",
		6:  "Perfil de Pessoa em Desenvolvimento de Parcerias Hierárquicas: Uma pessoa que já demonstra capacidade de estabelecer uma relação de parceria com a figura de autoridade, embora essa habilidade ainda esteja em processo de aprimoramento. Possivelmente, no passado, apresentava traços de submissão, mas agora busca construir conexões mais equilibradas e assertivas.",
		7:  "Perfil de Pessoa Submissa por Necessidade Contextual: Esse indivíduo tende a adotar uma postura de submissão em relação à figura de autoridade, não devido à falta de conhecimento ou competência, mas por estar em uma situação que o obriga a agir dessa forma no momento. Essa é uma habilidade que pode ser trabalhada e desenvolvida com o tempo.",
		8:  "Perfil de Pessoa Insegura Frente à Autoridade: Uma pessoa competente e qualificada, mas que enfrenta dificuldades para se posicionar diante de figuras de autoridade devido a sentimentos de insegurança. Isso resulta em uma postura submissa, ainda que seja algo contrário ao seu verdadeiro potencial.",
		9:  "Perfil de Pessoa com Necessidade de Aceitação: Alguém que valoriza intensamente o vínculo com superiores, motivado por uma grande necessidade de aceitação. Por isso, tende a adotar uma postura de submissão, obedecendo mesmo em situações que lhe causam desconforto. Esse comportamento reflete uma preocupação em agradar, ainda que isso comprometa seu bem-estar.",
		10: "Perfil de Pessoa com Necessidade de Aceitação: Alguém que valoriza intensamente o vínculo com superiores, motivado por uma grande necessidade de aceitação. Por isso, tende a adotar uma postura de submissão, obedecendo mesmo em situações que lhe causam desconforto. Esse comportamento reflete uma preocupação em agradar, ainda que isso comprometa seu bem-estar.",
	},
	10: {
		0:  "Pessoa que demonstra flexibilidade no que diz respeito ao cumprimento de normas, regras, valores e metodologias predefinidas. Foca principalmente no objetivo a ser alcançado, definindo de forma autônoma as melhores maneiras de realizar o trabalho. Possui um perfil criativo, capaz de encontrar soluções inovadoras, além de habilidade para delegar tarefas de maneira eficiente, contribuindo para a produtividade e o sucesso coletivo.",
		1:  "Pessoa que demonstra flexibilidade no que diz respeito ao cumprimento de normas, regras, valores e metodologias predefinidas. Foca principalmente no objetivo a ser alcançado, definindo de forma autônoma as melhores maneiras de realizar o trabalho. Possui um perfil criativo, capaz de encontrar soluções inovadoras, além de habilidade para delegar tarefas de maneira eficiente, contribuindo para a produtividade e o sucesso coletivo.",
		2:  "Pessoa que demonstra flexibilidade no que diz respeito ao cumprimento de normas, regras, valores e metodologias predefinidas. Foca principalmente no objetivo a ser alcançado, definindo de forma autônoma as melhores maneiras de realizar o trabalho. Possui um perfil criativo, capaz de encontrar soluções inovadoras, além de habilidade para delegar tarefas de maneira eficiente, contribuindo para a produtividade e o sucesso coletivo.",
		3:  "Pessoa que demonstra flexibilidade ao lidar com normas, regras, valores e metodologias, adaptando-se facilmente às exigências. Embora apresente uma leve inclinação a aceitar normas de forma passiva, essa característica não prejudica sua capacidade criativa. Além disso, possui habilidade para delegar tarefas de maneira eficiente e consegue distinguir claramente entre normas estabelecidas e padrões de execução, garantindo uma abordagem prática e inovadora.",
		4:  "Pessoa que apresenta, inicialmente, uma postura um tanto rígida, caracterizada por uma tendência a seguir normas de forma excessiva. Mostra preocupação não apenas com os objetivos a serem alcançados, mas também com os processos detalhados para realizá-los, o que pode levar ao investimento de energia em tarefas de pouca relevância. Essa abordagem sugere um bloqueio criativo, além de uma possível dificuldade em delegar responsabilidades de maneira eficaz.",
		5:  "Pessoa que apresenta, inicialmente, uma postura um tanto rígida, caracterizada por uma tendência a seguir normas de forma excessiva. Mostra preocupação não apenas com os objetivos a serem alcançados, mas também com os processos detalhados para realizá-los, o que pode levar ao investimento de energia em tarefas de pouca relevância. Essa abordagem sugere um bloqueio criativo, além de uma possível dificuldade em delegar responsabilidades de maneira eficaz.",
		6:  "Pessoa que apresenta, inicialmente, uma postura um tanto rígida, caracterizada por uma tendência a seguir normas de forma excessiva. Mostra preocupação não apenas com os objetivos a serem alcançados, mas também com os processos detalhados para realizá-los, o que pode levar ao investimento de energia em tarefas de pouca relevância. Essa abordagem sugere um bloqueio criativo, além de uma possível dificuldade em delegar responsabilidades de maneira eficaz.",
		7:  "Pessoa que segue de forma rigorosa as normas, regras, valores e metodologias que lhe são atribuídas, priorizando tanto o “que” fazer quanto o “como” executar. Mesmo que identifique conflitos ou inconsistências nas normas, tende a cumpri-las conforme solicitado, demonstrando uma postura altamente comprometida com a conformidade. No entanto, essa rigidez pode resultar em um bloqueio criativo, além de indicar dificuldades em delegar responsabilidades de maneira eficaz.",
		8:  "Pessoa que segue de forma rigorosa as normas, regras, valores e metodologias que lhe são atribuídas, priorizando tanto o “que” fazer quanto o “como” executar. Mesmo que identifique conflitos ou inconsistências nas normas, tende a cumpri-las conforme solicitado, demonstrando uma postura altamente comprometida com a conformidade. No entanto, essa rigidez pode resultar em um bloqueio criativo, além de indicar dificuldades em delegar responsabilidades de maneira eficaz.",
		9:  "Pessoa que segue estritamente as normas, regras, valores e metodologias estabelecidas, demonstrando um elevado compromisso com a conformidade e a execução precisa. Mostra grande preocupação tanto com o que deve ser feito quanto com o como realizar as tarefas, priorizando a obediência às diretrizes, mesmo que identifique eventuais conflitos ou inconsistências. Essa postura rígida pode resultar em um bloqueio criativo, além de indicar possíveis dificuldades em delegar responsabilidades de forma eficaz, impactando sua capacidade de trabalhar de maneira mais colaborativa e inovadora.",
		10: "Pessoa que segue estritamente as normas, regras, valores e metodologias estabelecidas, demonstrando um elevado compromisso com a conformidade e a execução precisa. Mostra grande preocupação tanto com o que deve ser feito quanto com o como realizar as tarefas, priorizando a obediência às diretrizes, mesmo que identifique eventuais conflitos ou inconsistências. Essa postura rígida pode resultar em um bloqueio criativo, além de indicar possíveis dificuldades em delegar responsabilidades de forma eficaz, impactando sua capacidade de trabalhar de maneira mais colaborativa e inovadora.",
	},
	11: {
		0:  "Perfil de Pessoa Dispersiva: Alguém com tendência a se envolver em várias atividades simultaneamente, mas que enfrenta dificuldades para priorizar tarefas e concluir projetos. Essa característica pode transmitir uma impressão de desorganização e pouca efetividade na gestão do tempo.",
		1:  "Perfil de Pessoa Multifuncional com Dificuldade de Foco: Essa pessoa busca realizar múltiplas tarefas ao mesmo tempo, porém encontra desafios significativos em mantê-las até o final devido à dispersão. Como resultado, pode ser percebida como alguém com baixa organização pessoal.",
		2:  "Perfil de Pessoa Multifuncional com Dificuldade de Foco: Essa pessoa busca realizar múltiplas tarefas ao mesmo tempo, porém encontra desafios significativos em mantê-las até o final devido à dispersão. Como resultado, pode ser percebida como alguém com baixa organização pessoal.",
		3:  "Perfil de Pessoa Dispersiva com Capacidade de Organização Moderada: Mostra disposição para lidar com diversas tarefas ao mesmo tempo e demonstra esforço em estabelecer prioridades, embora nem sempre consiga mantê-las devido à dispersão. Isso pode levar à percepção de desorganização em alguns contextos.",
		4:  "Perfil de Pessoa Adaptável e Estratégica: Um indivíduo com uma visão ampla, capaz de estabelecer e seguir prioridades de forma consistente. Apresenta ótima habilidade de adaptação a inovações e lida com imprevistos e emergências sem grande desgaste emocional. Demonstra flexibilidade e criatividade diante de mudanças bruscas, mantendo um excelente jogo de cintura.",
		5:  "Perfil de Pessoa Adaptável e Estratégica: Um indivíduo com uma visão ampla, capaz de estabelecer e seguir prioridades de forma consistente. Apresenta ótima habilidade de adaptação a inovações e lida com imprevistos e emergências sem grande desgaste emocional. Demonstra flexibilidade e criatividade diante de mudanças bruscas, mantendo um excelente jogo de cintura.",
		6:  "Perfil de Pessoa com Enfoque em Prioridades, mas com Desafios em Imprevistos: Trata-se de alguém que prioriza tarefas com clareza, mas enfrenta dificuldades para lidar com situações inesperadas ou emergenciais, o que pode ocasionar uma perda da visão de conjunto. Apesar disso, demonstra esforço em adaptar-se a mudanças abruptas, buscando lidar com situações “caóticas” de maneira resiliente e com menor desgaste emocional.",
		7:  "Perfil de Pessoa Focada e Perfeccionista: Essa pessoa apresenta uma abordagem estruturada, com forte habilidade para estabelecer prioridades. No entanto, tem dificuldade em lidar com imprevistos e demandas emergenciais. Possui uma tendência a concentrar-se exclusivamente em uma tarefa, o que pode limitar sua visão geral. Além disso, traços de perfeccionismo podem influenciar sua maneira de trabalhar e tomar decisões.",
		8:  "Perfil de Pessoa Focada e Perfeccionista: Essa pessoa apresenta uma abordagem estruturada, com forte habilidade para estabelecer prioridades. No entanto, tem dificuldade em lidar com imprevistos e demandas emergenciais. Possui uma tendência a concentrar-se exclusivamente em uma tarefa, o que pode limitar sua visão geral. Além disso, traços de perfeccionismo podem influenciar sua maneira de trabalhar e tomar decisões.",
		9:  "Perfil de Pessoa Focada e Metódica: Trata-se de alguém com uma abordagem altamente concentrada, que dedica sua atenção a uma única tarefa por vez. Esse foco resulta em trabalhos bem executados e de alta qualidade. Contudo, essa característica pode limitar sua percepção do panorama geral. A pessoa tende a estabelecer prazos mais longos para a realização das atividades, mas, eventualmente, pode ultrapassar o tempo previsto para entrega. Além disso, demonstra traços de perfeccionismo, o que pode dificultar sua adaptação a mudanças inesperadas ou demandas imprevistas.",
		10: "Perfil de Pessoa Focada e Metódica: Trata-se de alguém com uma abordagem altamente concentrada, que dedica sua atenção a uma única tarefa por vez. Esse foco resulta em trabalhos bem executados e de alta qualidade. Contudo, essa característica pode limitar sua percepção do panorama geral. A pessoa tende a estabelecer prazos mais longos para a realização das atividades, mas, eventualmente, pode ultrapassar o tempo previsto para entrega. Além disso, demonstra traços de perfeccionismo, o que pode dificultar sua adaptação a mudanças inesperadas ou demandas imprevistas.",
	},
	7: {
		0:  "Pessoa que demonstra equilíbrio ao selecionar e priorizar tarefas, sendo capaz de diferenciar com precisão os aspectos essenciais dos irrelevantes. Consegue delegar responsabilidades de forma eficiente, mantendo o foco no que realmente importa para o sucesso coletivo. Essa abordagem reflete uma liderança que promove o desenvolvimento contínuo da equipe.",
		1:  "Pessoa que demonstra equilíbrio ao selecionar e priorizar tarefas, sendo capaz de diferenciar com precisão os aspectos essenciais dos irrelevantes. Consegue delegar responsabilidades de forma eficiente, mantendo o foco no que realmente importa para o sucesso coletivo. Essa abordagem reflete uma liderança que promove o desenvolvimento contínuo da equipe.",
		2:  "Pessoa que apresenta boa habilidade em identificar tarefas importantes e eliminar distrações. Consegue delegar responsabilidades com facilidade, concentrando-se em questões mais estratégicas e relevantes para o progresso da equipe. Sua liderança é marcada pela capacidade de fomentar o crescimento de seus colaboradores.",
		3:  "Pessoa que ainda tende a se preocupar com detalhes desnecessários, mas demonstra progresso na delegação de tarefas. Ao aprender a focar no que é essencial, começa a promover um ambiente mais eficiente, contribuindo para o desenvolvimento e a autonomia de sua equipe.",
		4:  "Pessoa que apresenta dificuldades em evitar distrações com aspectos irrelevantes, dedicando energia a detalhes que poderiam ser delegados. Apesar disso, está em processo de aprendizado, buscando aprimorar suas habilidades de delegação para contribuir de forma mais eficaz com o crescimento e a eficiência da equipe.",
		5:  "Pessoa que se preocupa excessivamente com os detalhes devido à sua abordagem minuciosa. Tem dificuldade em delegar tarefas, preferindo realizar tudo por conta própria. Quando recebe o trabalho de outra pessoa, sente frequentemente a necessidade de refazê-lo, o que reflete uma tendência ao perfeccionismo e à busca constante por controle e qualidade.",
		6:  "Pessoa que se preocupa excessivamente com os detalhes devido à sua abordagem minuciosa. Tem dificuldade em delegar tarefas, preferindo realizar tudo por conta própria. Quando recebe o trabalho de outra pessoa, sente frequentemente a necessidade de refazê-lo, o que reflete uma tendência ao perfeccionismo e à busca constante por controle e qualidade.",
		7:  "Pessoa caracterizada por sua atenção meticulosa aos detalhes, o que pode dificultar a delegação de responsabilidades. Geralmente prefere executar as tarefas pessoalmente, e quando confia algo a outra pessoa, tende a revisar ou refazer o trabalho. Esse comportamento é guiado por traços de perfeccionismo e um alto padrão de exigência.",
		8:  "Pessoa que demonstra significativa dificuldade em delegar tarefas, preferindo centralizar o controle em si mesma. Muitas vezes, acaba se perdendo em detalhes pouco relevantes, o que pode comprometer sua eficiência geral. Seu perfil sugere traços marcantes de perfeccionismo e detalhismo, que influenciam sua forma de trabalhar.",
		9:  "Pessoa que demonstra significativa dificuldade em delegar tarefas, preferindo centralizar o controle em si mesma. Muitas vezes, acaba se perdendo em detalhes pouco relevantes, o que pode comprometer sua eficiência geral. Seu perfil sugere traços marcantes de perfeccionismo e detalhismo, que influenciam sua forma de trabalhar.",
		10: "Pessoa que demonstra significativa dificuldade em delegar tarefas, preferindo centralizar o controle em si mesma. Muitas vezes, acaba se perdendo em detalhes pouco relevantes, o que pode comprometer sua eficiência geral. Seu perfil sugere traços marcantes de perfeccionismo e detalhismo, que influenciam sua forma de trabalhar.",
	},
	13: {
		0:  "Pessoa de Sensibilidade Elevada e Postura Passiva: Um indivíduo muito sensível que busca evitar tanto ferir os outros quanto ser ferido. Geralmente evita reivindicar seu espaço ou confrontar o grupo, adotando uma postura passiva frente a problemas. Essa atitude pode resultar em omissão e na incapacidade de resolver conflitos de forma eficaz.",
		1:  "Pessoa de Sensibilidade Elevada e Postura Passiva: Um indivíduo muito sensível que busca evitar tanto ferir os outros quanto ser ferido. Geralmente evita reivindicar seu espaço ou confrontar o grupo, adotando uma postura passiva frente a problemas. Essa atitude pode resultar em omissão e na incapacidade de resolver conflitos de forma eficaz.",
		2:  "Pessoa de Sensibilidade Elevada e Postura Passiva: Um indivíduo muito sensível que busca evitar tanto ferir os outros quanto ser ferido. Geralmente evita reivindicar seu espaço ou confrontar o grupo, adotando uma postura passiva frente a problemas. Essa atitude pode resultar em omissão e na incapacidade de resolver conflitos de forma eficaz.",
		3:  "Pessoa Sensível e Conflitante com Passividade: Alguém que valoriza o bem-estar dos outros e, por isso, evita causar conflitos. Em situações de confronto, tende a adotar uma postura passiva, o que pode levar ao adiamento ou até à falta de resolução dos problemas.",
		4:  "Pessoa em Processo de Superação da Passividade: Apresenta certa inclinação para a passividade diante de conflitos ou problemas, mas demonstra esforço consciente para mudar sua postura. Está começando a enfrentar as dificuldades e resolver questões de forma mais proativa.",
		5:  "Pessoa Equilibrada e Diplomática em Conflitos: Um indivíduo que mantém um equilíbrio saudável entre posturas agressivas e passivas. É capaz de lidar com conflitos de forma habilidosa e diplomática, enfrentando os problemas diretamente e buscando soluções eficazes.",
		6:  "Pessoa Equilibrada e Diplomática em Conflitos: Um indivíduo que mantém um equilíbrio saudável entre posturas agressivas e passivas. É capaz de lidar com conflitos de forma habilidosa e diplomática, enfrentando os problemas diretamente e buscando soluções eficazes.",
		7:  "Pessoa com Tendência à Agressividade em Situações Tensas: Alguém que geralmente demonstra certo equilíbrio entre atitudes agressivas e passivas, mas que, em situações de alta tensão, pode inclinar-se para comportamentos agressivos. Essa tendência pode levar a explosões emocionais durante momentos de conflito.",
		8:  "Pessoa Agressiva e Resolutiva, mas Explosiva: Um indivíduo que enfrenta os conflitos com atitudes assertivas, às vezes chegando à agressividade. Apesar de resolver as questões que o incomodam, seu comportamento pode ferir outras pessoas. Costuma ser do tipo explosivo e, paradoxalmente, também se magoa com facilidade.",
		9:  "Pessoa com Postura Agressiva e Pouca Diplomacia: Uma pessoa que, diante de conflitos, adota uma postura agressiva e direta. Sua abordagem pode causar ferimentos emocionais nos outros devido à falta de diplomacia. Ao mesmo tempo, é sensível a críticas ou comentários que percebe como ofensivos, o que a deixa vulnerável emocionalmente.",
		10: "Pessoa com Postura Agressiva e Pouca Diplomacia: Uma pessoa que, diante de conflitos, adota uma postura agressiva e direta. Sua abordagem pode causar ferimentos emocionais nos outros devido à falta de diplomacia. Ao mesmo tempo, é sensível a críticas ou comentários que percebe como ofensivos, o que a deixa vulnerável emocionalmente.",
	},
	14: {
		0:  "Perfil de Pessoa com Controle Emocional Extremamente Frágil: Um indivíduo com controle emocional muito baixo, que reage de maneira explosiva em praticamente qualquer situação. Esse comportamento pode gerar dificuldades nos relacionamentos e prejudicar sua imagem. Apesar disso, não costuma guardar rancores ou ressentimentos, demonstrando transparência no que pensa ou sente. Pode ser descrito como alguém de “estopim curto”.",
		1:  "Perfil de Pessoa com Baixo Controle Emocional e Reações Explosivas: Apresenta pouca habilidade para controlar suas emoções, reagindo de maneira explosiva, o que pode impactar negativamente suas relações interpessoais e sua reputação. Embora seja do tipo “estopim curto”, geralmente não retém mágoas e age com transparência em relação aos seus sentimentos e pensamentos.",
		2:  "Perfil de Pessoa com Baixo Controle Emocional e Reações Explosivas: Apresenta pouca habilidade para controlar suas emoções, reagindo de maneira explosiva, o que pode impactar negativamente suas relações interpessoais e sua reputação. Embora seja do tipo “estopim curto”, geralmente não retém mágoas e age com transparência em relação aos seus sentimentos e pensamentos.",
		3:  "Perfil de Pessoa com Controle Emocional Frágil em Situações de Insegurança: Mostra um controle emocional delicado, especialmente em cenários onde se sente vulnerável. Essa fragilidade pode levá-lo a explosões emocionais, comprometendo sua imagem. Apesar disso, mantém um comportamento transparente e não guarda rancores ou ressentimentos.",
		4:  "Perfil de Pessoa em Desenvolvimento de Controle Emocional: Já demonstra um bom controle emocional, reflexo de um processo de evolução. Provavelmente foi, no passado, alguém de “estopim curto”, mas agora se preocupa em estabelecer relações transparentes, expressando seus sentimentos de maneira mais equilibrada.",
		5:  "Perfil de Pessoa com Maturidade Emocional: Uma pessoa que alcançou um nível significativo de equilíbrio emocional. Não se posiciona de forma passiva ou agressiva, agindo de maneira assertiva em suas interações cotidianas. Sabe expressar suas emoções com transparência e serenidade.",
		6:  "Perfil de Pessoa com Traços de Repressão Emocional: Um indivíduo que já demonstra preocupação em expressar seus sentimentos, mas que ainda luta contra padrões de repressão emocional. Essa dificuldade pode levá-lo a não revelar completamente o que pensa ou sente.",
		7:  "Perfil de Pessoa com Tendência à Repressão Emocional: Demonstra algum equilíbrio emocional, mas tende a reprimir suas emoções. Essa característica pode torná-lo suscetível a desenvolver problemas psicossomáticos devido à internalização de seus sentimentos.",
		8:  "Perfil de Pessoa com Controle Emocional Rigidez Excessiva: Alguém que exerce um forte controle sobre suas emoções, optando por reprimi-las ou bloqueá-las. Essa postura frequentemente leva à internalização dos sentimentos, aumentando o risco de desenvolver doenças psicossomáticas.",
		9:  "Perfil de Pessoa com Controle Emocional Rigidez Excessiva: Alguém que exerce um forte controle sobre suas emoções, optando por reprimi-las ou bloqueá-las. Essa postura frequentemente leva à internalização dos sentimentos, aumentando o risco de desenvolver doenças psicossomáticas.",
		10: "Perfil de Pessoa com Implosão Emocional: Um indivíduo que tem grande dificuldade em expressar suas emoções, optando por internalizá-las intensamente. Essa característica pode torná-lo propenso à somatização de seus problemas, eventualmente buscando alívio emocional em comportamentos prejudiciais, como o uso de substâncias.",
	},
	15: {
		0:  "Pessoa com Tendência Conservadora e Resistência a Mudanças: Um indivíduo que valoriza e preserva os hábitos aos quais está acostumado, apresentando grande dificuldade em aceitar mudanças e inovações. Essa resistência pode resultar no bloqueio de novas ideias ou adaptações necessárias.",
		1:  "Pessoa com Tendência Conservadora e Resistência a Mudanças: Um indivíduo que valoriza e preserva os hábitos aos quais está acostumado, apresentando grande dificuldade em aceitar mudanças e inovações. Essa resistência pode resultar no bloqueio de novas ideias ou adaptações necessárias.",
		2:  "Pessoa com Tendência Conservadora e Resistência a Mudanças: Um indivíduo que valoriza e preserva os hábitos aos quais está acostumado, apresentando grande dificuldade em aceitar mudanças e inovações. Essa resistência pode resultar no bloqueio de novas ideias ou adaptações necessárias.",
		3:  "Pessoa Conservadora com Dificuldade de Adaptação: Alguém que tende a manter os costumes e rotinas tradicionais, enfrentando desafios para se ajustar a mudanças e inovações. Essa postura pode levar a comportamentos que bloqueiem progressos e adaptações.",
		4:  "Pessoa Reservada frente a Mudanças e Inovações: Demonstra alguma abertura para mudanças, mas ainda enfrenta resistência interna. Adapta-se com dificuldade a novas situações, agindo com cautela e reserva.",
		5:  "Pessoa Adaptável e Aberta às Mudanças: Alguém que já aceita bem mudanças e inovações, mostrando capacidade de adaptação. Consegue ajustar-se às novas situações de maneira eficaz e adequada aos tempos modernos.",
		6:  "Pessoa Ágil e Proativa diante de Mudanças: Um indivíduo com alta receptividade às mudanças e inovações, adaptando-se rapidamente às novas situações. Mostra tendência a desejar que os processos avancem com rapidez, impulsionando a concretização de resultados.",
		7:  "Pessoa Ansiosa e Impaciente em Mudanças: Adapta-se bem a novas circunstâncias, mas demonstra uma ansiedade marcante e grande pressa para que os acontecimentos se desenrolem. Essa característica pode gerar frustrações quando o ritmo das mudanças não atende suas expectativas.",
		8:  "Pessoa Ansiosa e Impaciente em Mudanças: Adapta-se bem a novas circunstâncias, mas demonstra uma ansiedade marcante e grande pressa para que os acontecimentos se desenrolem. Essa característica pode gerar frustrações quando o ritmo das mudanças não atende suas expectativas.",
		9:  "Pessoa Ansiosa e Impaciente em Mudanças: Adapta-se bem a novas circunstâncias, mas demonstra uma ansiedade marcante e grande pressa para que os acontecimentos se desenrolem. Essa característica pode gerar frustrações quando o ritmo das mudanças não atende suas expectativas.",
		10: "Pessoa Focada em Velocidade, mas com Perda de Qualidade: Um indivíduo que prioriza a rapidez na implementação de mudanças, frequentemente sacrificando a qualidade dos resultados. Essa postura pode prejudicar a eficácia e o impacto das inovações aplicadas.",
	},
	16: {
		0:  "Pessoa com Dificuldade em Estabelecer Vínculos de Intimidade: Um indivíduo que encontra desafios em criar laços profundos, apesar de ter uma necessidade latente de contato afetivo. Protege-se ao racionalizar suas emoções, preferindo explicar a lógica por trás delas em vez de expressar o que sente. Isso pode dificultar sua capacidade de compartilhar problemas e buscar apoio.",
		1:  "Pessoa com Dificuldade em Estabelecer Vínculos de Intimidade: Um indivíduo que encontra desafios em criar laços profundos, apesar de ter uma necessidade latente de contato afetivo. Protege-se ao racionalizar suas emoções, preferindo explicar a lógica por trás delas em vez de expressar o que sente. Isso pode dificultar sua capacidade de compartilhar problemas e buscar apoio.",
		2:  "Pessoa com Baixa Expressão de Afetividade e Altas Expectativas: Apresenta dificuldade em demonstrar afeto em suas interações e, quando forma vínculos, é extremamente exigente com aqueles de quem gosta. Apesar de sua necessidade de carinho, não se permite mostrar suas emoções, o que também pode limitar sua habilidade de dividir problemas.",
		3:  "Pessoa que Mantém Boas Relações Afetivas com Limites Claros: Consegue estabelecer relações afetivas saudáveis, demonstrando habilidade em separar claramente questões emocionais do âmbito profissional. Evita misturar amizades com relações de trabalho, mantendo os dois aspectos bem delimitados.",
		4:  "Pessoa que Mantém Boas Relações Afetivas com Limites Claros: Consegue estabelecer relações afetivas saudáveis, demonstrando habilidade em separar claramente questões emocionais do âmbito profissional. Evita misturar amizades com relações de trabalho, mantendo os dois aspectos bem delimitados.",
		5:  "Pessoa Afetiva com Tendência a Excesso: Uma pessoa que estabelece conexões emocionais intensas, mas que, em alguns casos, pode prejudicar-se por causa de sua alta carga de afetividade. Essa característica sugere traços de carência emocional que influenciam suas interações.",
		6:  "Pessoa Muito Afetiva e Propensa a Concessões Exageradas: Um indivíduo com um perfil altamente carinhoso em seus relacionamentos, que pode sofrer impactos negativos ao fazer concessões excessivas às pessoas de quem gosta. Essa atitude reflete uma necessidade emocional de afeto que pode comprometer sua postura equilibrada.",
		7:  "Pessoa Muito Afetiva e Propensa a Concessões Exageradas: Um indivíduo com um perfil altamente carinhoso em seus relacionamentos, que pode sofrer impactos negativos ao fazer concessões excessivas às pessoas de quem gosta. Essa atitude reflete uma necessidade emocional de afeto que pode comprometer sua postura equilibrada.",
		8:  "Pessoa Afetiva com Dificuldade de Separação entre Afetividade e Trabalho: Alguém que demonstra grande sensibilidade emocional e uma necessidade constante de reconhecimento. Essa característica pode dificultar a separação entre a afetividade e as relações de trabalho, evidenciando traços de carência emocional.",
		9:  "Pessoa Altamente Afetiva e Carente de Reconhecimento: Um indivíduo que tem necessidade intensa de contato emocional e busca frequentemente validação sobre ser querido ou apreciado pelos outros. É generoso em demonstrar afeto, mas espera o mesmo em troca. Essa carência emocional alimenta sua busca por reconhecimento constante.",
		10: "Pessoa Altamente Afetiva e Carente de Reconhecimento: Um indivíduo que tem necessidade intensa de contato emocional e busca frequentemente validação sobre ser querido ou apreciado pelos outros. É generoso em demonstrar afeto, mas espera o mesmo em troca. Essa carência emocional alimenta sua busca por reconhecimento constante.",
	},
	20: {
		0:  "Pessoa com Sinais de Desmotivação e Baixa Autoestima: Apresenta sinais evidentes de desmotivação no ambiente de trabalho, com dificuldades significativas em reconhecer e valorizar suas próprias capacidades. Adota uma postura passiva e reprimida, o que limita sua iniciativa para conquistar novos espaços e oportunidades.",
		1:  "Pessoa com Sinais de Desmotivação e Baixa Autoestima: Apresenta sinais evidentes de desmotivação no ambiente de trabalho, com dificuldades significativas em reconhecer e valorizar suas próprias capacidades. Adota uma postura passiva e reprimida, o que limita sua iniciativa para conquistar novos espaços e oportunidades.",
		2:  "Pessoa com Pouca Exigência de Si Mesma e Desmotivada: Apesar de ter consciência de suas habilidades e potencial, demonstra desmotivação em relação ao trabalho. Esse sentimento pode estar associado a uma percepção de estar sendo subaproveitada, o que diminui sua proatividade e engajamento.",
		3:  "Pessoa Subaproveitada e Desmotivada no Trabalho: Embora reconheça suas capacidades e pontos fortes, essa pessoa exibe sinais de desmotivação. A sensação de estar subaproveitada pode ser um fator-chave para sua dificuldade em encontrar satisfação profissional.",
		4:  "Pessoa Ligeiramente Desmotivada, mas com Potencial: Mesmo conhecendo bem suas habilidades e potencialidades, pode apresentar uma leve desmotivação que a impede de avançar em suas metas de vida. Essa condição possivelmente está ligada à percepção de estar sendo subaproveitada.",
		5:  "Pessoa Motivada e Ambiciosa em Busca de Crescimento: Um indivíduo consciente de suas competências, que estabelece metas claras e demonstra uma forte necessidade de crescimento pessoal e profissional. Mostra-se motivado e ambicioso, perseguindo seus objetivos de maneira consistente e determinada.",
		6:  "Pessoa Motivada e Ambiciosa em Busca de Crescimento: Um indivíduo consciente de suas competências, que estabelece metas claras e demonstra uma forte necessidade de crescimento pessoal e profissional. Mostra-se motivado e ambicioso, perseguindo seus objetivos de maneira consistente e determinada.",
		7:  "Pessoa Ambiciosa com Metas Arrojadas: Reconhece seu potencial e trabalha com determinação para alcançar suas metas. No entanto, tende a fixar objetivos muito ambiciosos, o que pode levar a frustrações caso não sejam atingidos. Ainda assim, permanece motivada em sua busca por realizações.",
		8:  "Pessoa Ambiciosa com Alta Expectativa de Sucesso: Um indivíduo que estabelece metas elevadas tanto para si quanto para seu trabalho. No entanto, a dificuldade em lidar com a frustração ao não alcançar esses objetivos pode gerar desmotivação e sentimentos de insatisfação.",
		9:  "Pessoa Ambiciosa com Alta Expectativa de Sucesso: Um indivíduo que estabelece metas elevadas tanto para si quanto para seu trabalho. No entanto, a dificuldade em lidar com a frustração ao não alcançar esses objetivos pode gerar desmotivação e sentimentos de insatisfação.",
		10: "Pessoa Altamente Ambiciosa e Propensa à Frustração: Demonstra ambição e estabelece metas muito distantes de sua realidade atual. Essa característica pode levá-la a se sentir frustrada e desmotivada, comprometendo sua motivação e capacidade de manter-se no caminho para o sucesso.",
	},
	17: {
		0:  "Pessoa com Baixa Autoestima e Reserva: Um indivíduo que demonstra baixa autoestima e dificuldade em reconhecer seu próprio valor. Essa limitação reflete-se em sua incapacidade de vender sua imagem, motivada por uma postura tímida e reservada.",
		1:  "Pessoa Reservada com Confusão entre Marketing Pessoal e Exibicionismo: Apresenta um comportamento tímido e reservado, aliado à baixa autoestima. Enfrenta dificuldades em promover sua própria imagem, o que pode estar ligado a questões culturais. Confunde a prática de marketing pessoal com exibicionismo, o que limita sua capacidade de destacar-se.",
		2:  "Pessoa Reservada com Confusão entre Marketing Pessoal e Exibicionismo: Apresenta um comportamento tímido e reservado, aliado à baixa autoestima. Enfrenta dificuldades em promover sua própria imagem, o que pode estar ligado a questões culturais. Confunde a prática de marketing pessoal com exibicionismo, o que limita sua capacidade de destacar-se.",
		3:  "Pessoa em Transição, Buscando Confiança para Expor Ideias: Um indivíduo que ainda enfrenta algum desafio ao promover sua imagem devido à timidez e reserva, mas que já demonstra confiança suficiente para expor suas ideias com segurança. Apesar disso, continua a confundir marketing pessoal com exibicionismo, o que pode restringir seu potencial.",
		4:  "Pessoa Segura e Capaz de Valorizar-se: Uma pessoa que confia em seu potencial, apresenta uma autoimagem positiva e sabe valorizar suas qualidades. Essa confiança permite-lhe vender suas ideias de forma assertiva e segura.",
		5:  "Pessoa Confiante, mas com Tendência a Exageros: Um indivíduo com boa autoestima, que sabe promover sua imagem, mas que pode demonstrar traços de orgulho e uma inclinação a aparecer. Essa atitude, em alguns casos, pode incomodar outras pessoas, que a interpretam como convencimento. Esse comportamento pode estar vinculado a uma insegurança subjacente.",
		6:  "Pessoa Orgulhosa com Traços de Exibicionismo: Demonstra confiança em si mesma e promove sua imagem com desenvoltura, mas com sinais de exibicionismo. Essa postura pode causar desconforto entre os demais, que a consideram convencida ou inoportuna. Tal atitude pode ser reflexo de uma insegurança emocional mais profunda.",
		7:  "Pessoa Orgulhosa com Traços de Exibicionismo: Demonstra confiança em si mesma e promove sua imagem com desenvoltura, mas com sinais de exibicionismo. Essa postura pode causar desconforto entre os demais, que a consideram convencida ou inoportuna. Tal atitude pode ser reflexo de uma insegurança emocional mais profunda.",
		8:  "Pessoa Confiante, mas com Traços de Exibicionismo: Trata-se de um indivíduo que demonstra orgulho de si mesmo e confiança em sua imagem, com uma inclinação a destacar-se em ambientes sociais ou profissionais. Essa postura, entretanto, pode incluir elementos de exibicionismo que, por vezes, causam desconforto em outras pessoas, levando-as a interpretá-lo como convencido ou inoportuno. Esse comportamento pode ser um reflexo de insegurança pessoal subjacente, manifestada pela necessidade de validação ou reconhecimento.",
		9:  "Pessoa Confiante, mas com Traços de Exibicionismo: Trata-se de um indivíduo que demonstra orgulho de si mesmo e confiança em sua imagem, com uma inclinação a destacar-se em ambientes sociais ou profissionais. Essa postura, entretanto, pode incluir elementos de exibicionismo que, por vezes, causam desconforto em outras pessoas, levando-as a interpretá-lo como convencido ou inoportuno. Esse comportamento pode ser um reflexo de insegurança pessoal subjacente, manifestada pela necessidade de validação ou reconhecimento.",
		10: "Pessoa Exibicionista com Tendência à Vaidade: Um indivíduo que gosta de se destacar e prioriza a imagem pessoal em detrimento de resultados concretos. Sua vaidade pode indicar insegurança emocional, além de causar possíveis problemas de aceitação no grupo em que convive.",
	},
	18: {
		0:  "Pessoa com Dificuldade em Interagir com Grupos: Enfrenta grandes desafios em lidar com ambientes coletivos, optando frequentemente por evitá-los. Essa tendência ao isolamento pode estar relacionada a questões emocionais não resolvidas, que dificultam a construção de conexões interpessoais significativas.",
		1:  "Pessoa Individualista com Baixa Sensibilidade Social: Embora esteja presente fisicamente em um grupo, prefere realizar suas tarefas de forma independente, sem buscar interações ou colaboração ativa. É competente em suas funções individuais, mas apresenta pouca empatia ou sensibilidade em relação às necessidades dos outros membros do grupo.",
		2:  "Pessoa Firme e Independente nas Relações com Grupos: Reconhece a importância do grupo e participa dele, mas mantém uma postura assertiva e não se deixa influenciar facilmente pelos demais. É autônoma em suas decisões e preserva sua individualidade nas interações.",
		3:  "Pessoa Seleciona Relacionamentos Formais com Cautela: Mantém uma interação social mínima, suficiente para sustentar boas relações profissionais e formais. Prefere vínculos mais estreitos e intimidade com pequenos grupos, sendo bastante seletiva em suas escolhas de relacionamento.",
		4:  "Pessoa Reservada com Boa Adequação Social: Demonstra preocupação com as necessidades do grupo e consegue adaptar-se ao convívio social. Porém, tende a ser mais reservada, preferindo construir relações mais próximas e profundas com poucas pessoas. No contexto formal, lida bem com equipes e mantém interações saudáveis.",
		5:  "Pessoa Socialmente Sensível e Colaborativa: Um indivíduo atento às necessidades do grupo e com boa adequação social. Suas decisões geralmente são alinhadas aos interesses da equipe, contribuindo para manter um relacionamento interpessoal harmonioso e saudável.",
		6:  "Pessoa Sensível com Tendência a Fazer Concessões: Apresenta sensibilidade às necessidades do grupo e boa integração social. No entanto, por depender de um certo apoio emocional das pessoas, pode realizar concessões para agradar, mesmo que isso comprometa seus próprios limites ou preferências.",
		7:  "Pessoa Dependente do Apoio do Grupo: Tem grande necessidade de validação e apoio do grupo. Mesmo quando não concorda com as opiniões dos outros, tende a aceitá-las para evitar conflitos e preservar o bom clima de trabalho. Esse comportamento pode refletir uma certa carência emocional, o que, em algumas situações, pode prejudicá-la.",
		8:  "Pessoa Dependente do Apoio do Grupo: Tem grande necessidade de validação e apoio do grupo. Mesmo quando não concorda com as opiniões dos outros, tende a aceitá-las para evitar conflitos e preservar o bom clima de trabalho. Esse comportamento pode refletir uma certa carência emocional, o que, em algumas situações, pode prejudicá-la.",
		9:  "Pessoa Protetora e Dependente do Grupo: Apresenta uma dependência marcante em relação ao apoio do grupo. Enfrenta dificuldades em recusar solicitações e demonstra uma forte inclinação a assumir responsabilidades excessivas pelo bem-estar coletivo. Essa atitude protetora pode, eventualmente, impactar negativamente tanto o seu desenvolvimento pessoal quanto o da equipe.",
		10: "Pessoa Protetora e Dependente do Grupo: Apresenta uma dependência marcante em relação ao apoio do grupo. Enfrenta dificuldades em recusar solicitações e demonstra uma forte inclinação a assumir responsabilidades excessivas pelo bem-estar coletivo. Essa atitude protetora pode, eventualmente, impactar negativamente tanto o seu desenvolvimento pessoal quanto o da equipe.",
	},
	19: {
		0:  "Pessoa com Sinais de Cansaço e Baixo Tônus Vital: Apresenta claros indícios de fadiga, acompanhados de um tônus vital extremamente baixo. Esse quadro sugere uma tendência à estafa, indicando a necessidade de atenção para evitar um possível agravamento.",
		1:  "Pessoa com Baixo Tônus Vital e Tendência ao Estresse: Encontra-se em um estado de baixa energia, que pode estar relacionado a problemas emocionais, excesso de trabalho ou uma combinação de ambos. Essa condição sugere uma predisposição ao estresse, exigindo medidas para restabelecer o equilíbrio.",
		2:  "Pessoa com Baixo Tônus Vital e Tendência ao Estresse: Encontra-se em um estado de baixa energia, que pode estar relacionado a problemas emocionais, excesso de trabalho ou uma combinação de ambos. Essa condição sugere uma predisposição ao estresse, exigindo medidas para restabelecer o equilíbrio.",
		3:  "Pessoa com Baixo Tônus Vital e Tendência ao Estresse: Encontra-se em um estado de baixa energia, que pode estar relacionado a problemas emocionais, excesso de trabalho ou uma combinação de ambos. Essa condição sugere uma predisposição ao estresse, exigindo medidas para restabelecer o equilíbrio.",
		4:  "Pessoa com Tendência Moderada ao Estresse: Demonstra sinais iniciais de estresse, possivelmente decorrentes de sobrecarga de trabalho, desafios emocionais ou ambos. Apesar das dificuldades, parece estar empenhada em melhorar essa situação.",
		5:  "Pessoa com Bom Tônus Vital e Desempenho Consistente: Apresenta um nível adequado de energia física, que permite o cumprimento eficaz de suas atividades e contribui para um desempenho sólido em diferentes contextos.",
		6:  "Pessoa com Bom Tônus Vital e Desempenho Consistente: Apresenta um nível adequado de energia física, que permite o cumprimento eficaz de suas atividades e contribui para um desempenho sólido em diferentes contextos.",
		7:  "Pessoa Energética, mas com Dificuldades de Concentração: Exibe alta energia física, o que proporciona facilidade de movimentação. Entretanto, essa característica pode comprometer sua concentração, já que demonstra uma inclinação para buscar deslocamentos frequentes.",
		8:  "Pessoa com Alta Energia e Propensão a Movimentos Desnecessários: Apresenta um nível elevado de energia física, aliado a dificuldades de concentração. Tende a realizar deslocamentos desnecessários, possivelmente em decorrência de sua necessidade constante de se manter em movimento.",
		9:  "Pessoa com Alta Energia e Propensão a Movimentos Desnecessários: Apresenta um nível elevado de energia física, aliado a dificuldades de concentração. Tende a realizar deslocamentos desnecessários, possivelmente em decorrência de sua necessidade constante de se manter em movimento.",
		10: "Pessoa com Excesso de Tônus Vital e Baixa Capacidade de Foco: Caracteriza-se por uma energia física excessiva, o que dificulta sua capacidade de permanecer parada. Essa inquietação pode gerar desafios consideráveis em relação à concentração e ao foco em atividades específicas.",
	},
}
